### PR TITLE
feat(loading): add ability to update content

### PR DESCRIPTION
**Pull request by ihadeed**
I thought it would be nice to be able to update the loading content dynamically.

I tried doing this this way and it worked:
```typescript
let loading: Loading = Loading.create({ content: 'initial content' });
this.nav.present(loading);
setTimeout(()=>this.loading.data = 'new content', 1000);
```

Might have to add `private data: any;` in the `Loading` class to prevent TS errors.

### CODE REVIEW

**Comment by manucorporat** [comment]
I think `setContent` would be a better naming in this case.

**Comment by ihadeed** [comment]
I agree, just edited it.

**Comment by royipressburger** [comment]
Like! +1

**Comment by brandyscarney** [comment]
Thanks! Could you submit this against the `master` branch instead of the `2.0` branch please? :)

**Pull request closed without merging**
