### PR TITLE
Modal backdrop choppiness fix

### PR DESCRIPTION
**Pull request by jabyrd3**
Fixes choppy animation when loading modal on low spec devices by using an opacity transition as opposed to rgba alpha channel transition, which is much more expensive in this case.

### CODE REVIEW

**Comment by jabyrd3** [comment]
Any progress on this? My team is working against my fork but I'd like to get them back on the main repo.

**Comment by jabyrd3** [comment]
If you want me to clean up this pull request before merging let me know. It's passing all tests and is noticeably more performant on low spec devices. I want to get my team back on ionic-main as soon as possible.

**Comment by adamdbradley** [comment]
Yes, would be able to create a clean commit with the fixes? Also, why are you calling it `.modal-fix`?

**Comment by adamdbradley** [comment]
https://github.com/driftyco/ionic/commit/a984624516caaf48f5d3ed38d0945404803cf719

**Pull request closed without merging**
