### PR TITLE
Adds Support for exposeAsideWhen for <ion-side-menu site="right">

### PR DESCRIPTION
**Pull request by JanPeCol**
Please check and merge

### CODE REVIEW

**Comment by mhartington** [comment]
So this appears to work already with 1.0 

http://codepen.io/mhartington/pen/WvpBQy

What exactly is this fixing?

**Comment by JanPeCol** [comment]
If you use in the 1.0 a left and right slide menu exposeAsideWhen will only work on the left side.
Not on the right, see http://codepen.io/anon/pen/bdEEZw and http://forum.ionicframework.com/t/side-menu-expose-aside-when-on-right-menu-will-not-work/22613

**Comment by mhartington** [comment]
So something I'm noticing in my tests is that if you have either side exposed, you can still drag to open the other side. While this does allow right sidemenus to be used, seem that there are still some issues with the PR. Would you be able to look into that and fix the issue?

**Comment by JanPeCol** [comment]
Sure, I'll do

**Comment by JanPeCol** [comment]
for safety, do you think this error?
bildschirmfoto 2015-06-10 um 16 19 02

**Comment by mhartington** [comment]
yep, thats the one

**Comment by mlynch** [comment]
Duplicate of #2328 which is now fixed and will be in 1.2

**Pull request closed without merging**
