### PR TITLE
fix(demos/config) fix for config page not updating. #9413

### PR DESCRIPTION
**Pull request by ncapito**
#### Short description of what this resolves:
Config demo was not updating when settings were saved.  

#### Changes proposed in this pull request:
- Move the setting of config from the ApiDemoPage to ApiDemoApp
- Add injectable Config to ApiDemoPage and sett `this.config=config.settings()`

**Ionic Version**: 1.x / 2.x
2.x

**Fixes**: #
#9413

### CODE REVIEW

**Comment by brandyscarney** [comment]
Thanks for the PR! Could you update it from master and I'll take a look at it? :)

**Comment by ncapito** [comment]
Yea it was a long time ago so it might take a little bit to get back up to speed and make sure other changes have not changed the need for this.  I'll try to get it back to you by tomorrow.

**Comment by brandyscarney** [comment]
Awesome thank you! Please make sure to run it using `gulp demos.watchProd --f=config` too. :)

**Comment by ncapito** [comment]
@brandyscarney  hopefully this isn't too dumb of a comment ;) but when i run `gulp demos.watchProd --f=config` and go to : http://localhost:8000/dist/demos/config/  it just gives me a blank screen and a bunch of 404 console errors : localhost:800/demos/config/build/main.css  and demos/config/build/main.js  any suggestions on what I'm doing wrong?

**Comment by brandyscarney** [comment]
@ncapito Ahh yeah the demos task got a little messed up with our recent change to work with app-scripts. The dev build needs a different `import` than the prod build in order to work. Hmm can you try modifying the code here: https://github.com/driftyco/ionic/blob/master/scripts/gulp/tasks/demos.prod.ts#L116-L124

to add the `--debug` flag like so:

```
    const scriptsCmd = spawnSync('ionic-app-scripts',
      ['build',
      '--debug',
      '--prod',
      '--sass', sassConfigPath,
      '--appEntryPoint', appEntryPoint,
      '--srcDir', distDir,
      '--wwwDir', distDir,
      '--tsconfig', tsConfig
      ]);
```

And then see if there are any errors in the output by running `gulp demos.prod --f=config` again?

**Comment by brandyscarney** [comment]
I went ahead and tested this against our latest build process. It looks good, thank you!

**Pull request merged**
