### PR TITLE
fix(rtl): add segment rtl support

### PR DESCRIPTION
**Pull request by AmitMY**
#### Short description of what this resolves:
add segment rtl support

#### Changes proposed in this pull request:
Fixes:
image

**Ionic Version**: 3.x

### CODE REVIEW

**Comment by brandyscarney** [comment]
Only issue I see with this is the thicker border width for the last 2 segments when there are more than 2 segment buttons:

screen shot 2017-04-13 at 4 58 44 pm

I have to head out for a bit but I can look into fixing it later or tomorrow if you don't. :)

**Comment by AmitMY** [comment]
@brandyscarney I think that fixes it.
Normally, everything has a border right, and only first need border left. here first does not need the left because it is (in ltr perspective) last

**Comment by brandyscarney** [comment]
@AmitMY Looks great! Thanks! :smile:

**Comment by manucorporat** [comment]
@brandyscarney @AmitMY I don't want to be touchy, but I think this is a over-complicated and difficult to maintain fix, why we just don't use:

```
[dir="rtl"] ion-segment {
  flex-direction: row-reverse;
}
```

?

**Comment by AmitMY** [comment]
@manucorporat I think I briefly considered it, then dismissed
The reason is that it reverses the order of the columns..

This is LTR:
image

This is RTL (before this fix):
image

And this is RTL with `row-reverse`:
image

Finally, this is RTL after this fix: (which is the desired behavior)
image

**Comment by manucorporat** [comment]
@AmitMY ok, I think I get it. Sorry for the ignorance :)

**Pull request merged**
