### PR TITLE
adding scroll-complete event to ionScroll directive

### PR DESCRIPTION
**Pull request by dioxmio**
#### Short description of what this resolves:

The onScrollComplete event is missing from ionScroll directive. This is very handy when using this directive with the paging option enabled. All the infrastructure to handle this event was done, just reusing it for this directive.

#### Changes proposed in this pull request:

-
-
-

**Ionic Version**: 1.x / 2.x

**Fixes**: #

### CODE REVIEW

**Comment by dioxmio** [comment]
@mlynch can you comment why this PR has been closed? this functionality is needed

**Comment by jgw96** [comment]
@dioximio hello! Sorry about this PR being closed, when we switched the Ionic 2 branch to master today it had the side affect of closing some pull requests. I don't seem to have the permissions to reopen this pull request, but will get one of my teammates to take a look at it tommorow. Thanks for contributing to Ionic!

**Comment by jgw96** [comment]
Hello @dioxmio , could you resubmit this pr to the `v1` branch? Unfortunately the repo has changed too much since we made ionic 2 the master branch to be able to reopen this pr.  Thanks!

**Comment by dioxmio** [comment]
create new PR: https://github.com/driftyco/ionic/pull/7129

**Pull request closed without merging**
