### PR TITLE
feat(app): add responsive utility attributes

### PR DESCRIPTION
**Pull request by brandyscarney**
#### Short description of what this resolves:
Adds responsive attributes for text alignment, transforms, and float.

#### Changes proposed in this pull request:

- moves breakpoint mixins to the ionic.mixins file
- adds responsive attributes for text alignment, transform, and
floating elements
- adds ability to turn these off so they don’t get added to the css
file using sass variables

**Ionic Version**: 3.x

**Fixes**: #10567

### CODE REVIEW

**Comment by mhartington** [comment]
👍

**Comment by anilthummar** [comment]
@brandyscarney 
I am getting error when i am creating new project in ionic 2 on window 10 operating system.
i am use following version of ionic 2,node ,cordova and nmp.

Please help me.
### C:\Users\Android>cordova -v
6.5.0
### C:\Users\Android>ionic -v
2.2.2
### C:\Users\Android>node -v
v7.8.0
### C:\Users\Android>npm -v
4.5.0

### Your system information:

 **ordova CLI: 6.5.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.8.0
Xcode version: Not installed**

# 
## My Error:
**E:\Ionic Data\Demo>ionic start --skippnpm
Starting Ionic Project wizard...
Using directory as root: E:\Ionic Data\Demo
√ Running start wizard:  http://localhost:8900/
Creating an Ionic 2.x app in E:\Ionic Data\Demo\Io2MyApp based on the tabs template.**

**Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
**Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
Installing npm packages (may take a minute or two)...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall**
Creating an Ionic 2.x app in E:\Ionic Data\Demo\Io2MyApp1 based on the tabs template.**

**Comment by mhartington** [comment]
@anilthummar this isn't really the place for this kind of support help. Please use the ionic forum or public slack channel. Thanks!

**Comment by anilthummar** [comment]
@mhartington 
Ok i will use ionic forum and public slack and Thanks for the reply.

**Pull request merged**
