### PR TITLE
Support `controllerAs` syntax in ion-nav-view (#3058, #2499) 

### PR DESCRIPTION
**Pull request by urish**

### CODE REVIEW

**Comment by thaiat** [comment]
+ 1

**Comment by paulogr** [comment]
+1
Em 14/05/2015 09:55, "Avi Haiat" <notifications@github.com> escreveu:

**Comment by ClemMakesApps** [comment]
+1

**Comment by cmartin81** [comment]
+1

**Comment by urish** [comment]
@Ionitron any chance of merging this?

**Comment by fabiosussetto** [comment]
Please guys this GOT to be working on ionic stable.

**Comment by ClemMakesApps** [comment]
Based on the tagging, this looks like it'll be added on next release

**Comment by Neophy7e** [comment]
Like it should have been added to the 1.1 version could anyone merge it ?

**Comment by mhartington** [comment]
There were a few other things that took priority. Will revisit this. 
You can still use controller as though, nothing is preventing you from doing so

```
controller: 'MainCtrl as main'
```

**Comment by urish** [comment]
@mhartington thanks for the response!

At least in my case, the `controller: 'MainCtrl as main'` complicated things, as my paradigm is to declare controllers as ES6 classes, then use `controller: MainCtrl` instead of having to register them in angular and then reference them by name. This is why I find this feature very useful. 

I hope that this makes sense to you :-)

**Comment by Neophy7e** [comment]
@mhartington I didn't know that I could use `controller: 'MainCtrl as main'`Thanks !

**Comment by cmartin81** [comment]
I use [ng-decorators](https://www.npmjs.com/package/ng-decorators) to create controller classes with ES6 decorators. And I need to reference to a class object and not a string. So that is why I cannot use 'MainCtrl as main' syntaks in my code.

**Comment by mhartington** [comment]
Makes sense, I realize that it's not a perfect solution for everyone. Which is why I want this in as well.

**Comment by mhartington** [comment]
@urish any chance you could provide a test for this?

**Comment by urish** [comment]
@mhartington yes

**Comment by urish** [comment]
@mhartington here we go :)

**Comment by mhartington** [comment]
@urish much obliged

**Comment by mhartington** [comment]
I derped the commit message, but this has now been added via a665d1d2091bde55f7b3bdc765f1e79b5b515e1d

Please test this out and report back any errors.

**Comment by urish** [comment]
Yay!

**Pull request closed without merging**
