### PR TITLE
feat(select): Add disabled status in Select Options

### PR DESCRIPTION
**Pull request by voliva**
#### Short description of what this resolves:
I needed some select options to show as disabled. In this pull request, I added the `@Input` `disabled` in the `Option` component, and passed it's value all the way through `Select` component up to the `Alert` component (that's where the actual checkbox/radiobutton is created).

**Ionic Version**: 2.0.0-beta.9

Sorry for not following the guidelines of posting first an issue. I made the bad practice of first implementing the solution, then reading the guidelines.

### CODE REVIEW

**Comment by manucorporat** [comment]
@voliva your PR looks! but can you explain your use case?

**Comment by voliva** [comment]
Sure, my use case was that I had a Select component with many items in there representing services that my business provides.

The thing is that some of these services are not available yet, so I wanted to show them as a "comming soon" placeholder, but I shouldn't be selectable, i.e. disabled.

**Comment by voliva** [comment]
I see that with beta.10 I will have to refractor things a bit. The merge conflict is not easy to solve.

**Comment by manucorporat** [comment]
@voliva right! the whole overlay for alert, action sheet has been refactored

**Comment by voliva** [comment]
@manucorporat Should be ready now!

I wonder though, maybe it would also make sense to disable all kinds of inputs if it's `AlertInputOptions` is set as disabled, for consistency? I can't see the use of creating an Alert with their inputs disabled, but then maybe it's confusing to have one `disabled` parameter if it only works on radio buttons or checkboxes.

**Comment by adamdbradley** [comment]
Awesome thanks!

**Pull request merged**
