### PR TITLE
[ionicHistory] add method to remove the back view

### PR DESCRIPTION
**Pull request by ashconnell**
solves issue #3750

Adds a method `$ionicHistory.removeBackView()` which removes the cached view, element, scope, and rejigs the history. I'm already using this in production in various use-cases. 

This predominantly solves the issue where in most angular applications you can use `$state.go('app.foo', { location: 'replace' })` except in ionic, the history is managed manually - this is the solution.

Would be good to have it part of the core!

I'm working on the method `$ionicHistory.removeFromHistory(stateName/id)` which we also need for our app - and the ionic community would also benefit from this going forward. Keep an eye out.

### CODE REVIEW

**Comment by piotrowski** [comment]
+1

**Comment by danicomas** [comment]
+1

**Comment by pesimeao** [comment]
Any progress in this PR? It would be great to include in the next version!

**Comment by alwayrun** [comment]
+1

**Comment by hossam9995** [comment]
+1

**Comment by danbucholtz** [comment]
Hi @ashconnell, can you write some unit tests for this?  We can't merge this without tests.

Thanks,
Dan

**Comment by danbucholtz** [comment]
I wrote a test and merged due to demand.  Thank you for your contribution!  We appreciate it!

Thanks,
Dan

**Comment by kmturley** [comment]
If I use the ui-router location replace, it doesn't work

     $state.go(toState.name, { location: 'replace' });

but using angular location replace does work:

     $location.path($state.href(toState.name)).replace();

**Pull request merged**
