### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by glaucocustodio**
#### Changes proposed in this pull request:

-
-
-

**Ionic Version**: 1.x / 2.x

**Fixes**: #

### CODE REVIEW

**Comment by r7sy** [comment]
I don't think uninstalling is necessary , is it ?

**Comment by glaucocustodio** [comment]
I had the previous version installed and I got stuck till I remove it.

**Comment by brandyscarney** [comment]
It doesn't hurt to uninstall it first. Thanks :)

**Comment by RafaelKr** [comment]
@r7sy It was necessary for me, else I got this errors:

```
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! path /usr/local/lib/node_modules/.staging/ansi-392b32ed
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!    ~/npm-debug.log
npm ERR! code 1
```

**Comment by r7sy** [comment]
@glaucocustodio  @RafaelKr  good to know  
thanks .

**Pull request merged**
