### PR TITLE
feat(slides): Added move event onSlideMove

### PR DESCRIPTION
**Pull request by edanweis**
My first ever PR. Definitely need some guidance here. Will docs and tests need updating before this is merged?  This event may be useful for [parallax effects](http://www.joshmorony.com/how-to-create-a-directive-in-ionic-2-parallax-header/) in slides, where scroll events won't work.

### CODE REVIEW

**Comment by adamdbradley** [comment]
I'm concerned about performance on low-end devices. Have you noticed any performance differences when swiping between slides, with and without this update, on slower android devices?

**Comment by edanweis** [comment]
No, I haven't tested performance on low-end android devices. I assume performance losses would depend on what - if anything- was being executed on move. Are there alternatives to listening for touch / mouse movement in Angular 2, avoiding the use of Swiper?

**Comment by adamdbradley** [comment]
@brandyscarney with your updates to the slider, can you test this out too to make sure it doesn't bring down any swipe performance?

**Comment by edanweis** [comment]
Thanks so much @brandyscarney for your thorough reply. Have a great weekend! :smile:

**Pull request merged**
