### PR TITLE
fix(popover): fix popover position on Internet Explorer

### LINKED ISSUE #2861: bug: Popover position wrong on Windows Phone
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>windows</span>  

<span ionic-description>Popover position calculation doesn't work correctly on IE and the end result is that popovers gets rendered off viewport. See the screenshot below where the issue is highlighted with a red rectangle.

screen shot 2015-01-05 at 11 24 50

The issue is reproducible by opening http://codepen.io/ionic/pen/GpCst (and trying to see the popover). Same issue occurs on both desktop IE 11 and the IE mobile 11 on Windows Phone 8.1. Also, the issue is visible on Cordova-packaged apps run on Windows Phone 8.1.

The root cause seems to be the different value IE returns to $document[0].body.clientWidth when it is called to calculate the correct popover position.

The following diff fixes the issue:

```
diff --git a/js/angular/service/popover.js b/js/angular/service/popover.js
index 3bfa6eb..d410aac 100644
--- a/js/angular/service/popover.js
+++ b/js/angular/service/popover.js
@@ -93,8 +93,9 @@ function($ionicModal, $ionicPosition, $document, $window) {
     var buttonOffset = $ionicPosition.offset(targetEle);
     var popoverWidth = popoverEle.prop('offsetWidth');
     var popoverHeight = popoverEle.prop('offsetHeight');
-    var bodyWidth = $document[0].body.clientWidth;
-    // clientHeight doesn't work on all platforms for body
+    // Use innerWidth and innerHeight, because clientWidth and clientHeight
+    // doesn't work consistently for body on all platforms
+    var bodyWidth = $window.innerWidth;
     var bodyHeight = $window.innerHeight;
```

Tested briefly on iOS and Android and seems like the diff doesn't bring regressions to this functionality on those platforms.

</span>

<span is-issue-template></span>

### PR DESCRIPTION
**Pull request by vjrantal**
Closes #2861

### CODE REVIEW

**Comment by vjrantal** [comment]
To test for regressions, I run the E2E tests on desktop Chrome with ```gulp snapshot```. The results were the same with and without this change. Here are the popover-related results:

```
$ionicPopover-popover
  should init - pass
  should open left side ios popover - pass
  should close ios popover when clicking backdrop - fail
  should open middle ios popover - pass
  should open right ios popover - fail
  should open left side android popover - fail
  should close android popover when clicking backdrop - fail
  should open middle android popover - pass
  should open right android popover - fail
```

So some failures, but as said, same result before and after the contents of this pull request.

```gulp karma``` passes on my environment also with this pull request's content:

```
Chrome 39.0.2171 (Mac OS X 10.9.5): Executed 864 of 864 SUCCESS (6.959 secs / 6.869 secs)
```

By the way, to run the snapshot tests locally, I had to do two edits:

1. I noticed was that commit 7d000deb8b4361764cbb7ebb079e3b186c90daca changed the location to which demos ended up being generated so had to revert that for the test runner to find the demos.
2. The tests didn't execute if the IonicReporter was enabled in the configs like it was by default. As a workaround, I commented out the reporter from config/lib/ionic-snapshot.js line 138.

**Comment by vjrantal** [comment]
I'd like to check is this pull request ready to go in? The issue this fixes ( https://github.com/driftyco/ionic/issues/2861 ) seems to have gotten the ready label, but I am not sure if that means anything.

**Comment by dannyg** [comment]
I would like to see this pull request accepted as well, as it fixes the referenced issue.
Any update?

**Comment by perrygovier** [comment]
patched in 893fcbec5f97eb487d602ab2c19459924c0098b0 
Thanks!

**Pull request closed without merging**
