### PR TITLE
fix(spinner): make stop flag local. Fixes #4819

### LINKED ISSUE #4819: bug: Multiple ion-spinners (with same icon)
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If you have multiple ion-spinners with the same icon, and "destroys" one of them by for example ng-if the one with the ng-if is correctly destroyed and removed from DOM but the other spinner(s) with the same icon is getting stopped to and can't be used anymore. 

See example (notice the two ion-spinners with "android" icon):
http://codepen.io/dennishn/pen/OMNybR

Then you click the toggle, the first ion-spinner with "android" icon will be removed by ng-if and the other "android" spinner is getting stopped too. 

My hot-fix atm is not destroying my spinners but simply hide/show them with ng-hide or show but I don't think this is optimal behaviour. 

I have following scenario where I need two spinners: 

One spinner for loading some async content (which I want to remove then my content has been loaded as it's not needed anymore)

One spinner to show some progress, example clicking on a button by submitting data. 

I don't know if this is a "bug" or just how it's designed.</span>

<span is-issue-template></span>

### PR DESCRIPTION
**Pull request by richardsun29**

### CODE REVIEW

**Comment by PerfectionCSGO** [comment]
I applied this to my build but it didn't seem to fix it for PTR spinners after switching views.

**Comment by richardsun29** [comment]
Can you provide some code that shows this issue so that i can take a look?

**Comment by PerfectionCSGO** [comment]
<ion-refresher pulling-text="Trek om te synchronizeren..." on-refresh="mut.refresh()" pulling-icon="ion-android-arrow-down positive" spinner="android"></ion-refresher>

mut.refresh() always calls $scope.$broadcast('scroll.refreshComplete'); on complete. I've never made a codepen but I could try and make one if it is desired.

**Comment by PerfectionCSGO** [comment]
http://codepen.io/anon/pen/obLYwE This is the basic gist of what my setup looks like. I use the same spinner on two views, when switching to views the spinner dies. I can't seem to reproduce it on codepen but the issue persists on my devices.

**Comment by richardsun29** [comment]
Hmm pull to refresh spinner seems to work for me, with and without this patch. Maybe it's a device problem? I'm only able to do stuff with webview right now

**Comment by PerfectionCSGO** [comment]
I tempoarily fixed this by disabling stop() myself. For the scale of my app this doesn't seem to have an performance issues even on a Nokia Lumia 520.

**Comment by danbucholtz** [comment]
Hi @richardsun29,

This issue should be resolved in the nightly release on Ionic via a different PR.  Thank you very much for contributing and I'm sorry we can't merge your code.  We sincerely appreciate you submitting the PR.

Thanks,
Dan

**Pull request closed without merging**
