### PR TITLE
Item option swipe

### PR DESCRIPTION
**Pull request by edparsons**
Hi Guys, this is an added directive that lets users add a callback if a user swipes an item. I've built it on top of the existing item-option-button swipe code, so it should be really easy for people to use.

This is my first pull request to an open source project, so I'm not sure of the etiquette around this. If more work needs to be done to the code, best practice changes or anything please forgive me and point me in the right direction so I can fix it and re-submit. I love what you guys are doing with Ionic and would love to be a contributor.

### CODE REVIEW

**Comment by edparsons** [comment]
Hi, please still review the idea for inclusion but I've just found the contribute page http://ionicframework.com/contribute/#conventions and so let me write tests before this is merged in

**Comment by edparsons** [comment]
Tests written and it's passing jshint now

**Comment by perrygovier** [comment]
Thanks! This is great! Unfortunately, we're not adding any new features while we're in RC stage. I've added this to the 1.1 milestone for consideration after the 1.0

**Comment by edparsons** [comment]
Wow, thanks for the consideration Perry. I understand about no new feature for the RC, are you still adding bug fix pull requests, I have a couple of those waiting and wondering if I should wait until after RC or get them in when they're ready?

**Pull request closed without merging**
