### PR TITLE
Bind collection-repeat resize on view enter/leave

### PR DESCRIPTION
**Pull request by stianjensen**
Fixes driftyco/ionic#2935

I wasn't quite sure which events would be most appropriate. Might `afterEnter` and `beforeLeave` be even better?

### CODE REVIEW

**Comment by stianjensen** [comment]
In my tests, this also seems to fix issues like driftyco/ionic#2890

**Comment by panurge-ws** [comment]
I don't think this can fix #2935 because the $ionicModal.show() causes to call the 'resize' event. The view with collection-repeat is still active so it will perform a new render when showing the modal. If you put a console.log() inside the function rerenderOnResize() and call the $ionicModal.show() while you still are in the view with the collection-repeat, you will see the log. Hope it helps.

**Comment by stianjensen** [comment]
Hmm, that's right. I didn't realize the view is still active when a modal is presented in front.

**Comment by panurge-ws** [comment]
Unfortunately, we have also another issue: it seems that if put the view with collection-repeat inside the a tab, and then switch to another tab, the resize listener keeps to be attached because none of the $ionicView.afterLeave or $ionicView.leave are dispatched.

**Pull request merged**
