### PR TITLE
fix(list): consecutive inset lists with headers

### LINKED ISSUE #8412: Consecutive inset lists with header
Second list's header is not displayed correctly:
screen shot 2016-10-03 at 00 52 51

### PR DESCRIPTION
**Pull request by manucorporat**
#### Short description of what this resolves:
Fixes #8412 

After fix:
screen shot 2016-10-03 at 14 22 48

@brandyscarney can you review it?!

### CODE REVIEW

**Comment by brandyscarney** [comment]
I'll review this once I get the e2e tests up and running!

**Comment by manucorporat** [comment]
@brandyscarney try commenting out the fix, the e2e test should look bad ;)

**Comment by brandyscarney** [comment]
screen shot 2016-10-06 at 3 44 29 pm

**Comment by manucorporat** [comment]
Good catch. Adding tests and fix.

**Comment by manucorporat** [comment]
@brandyscarney fixed
screen shot 2016-10-06 at 22 32 02

**Pull request merged**
