### PR TITLE
fix null/undefined references

### PR DESCRIPTION
**Pull request by soumak77**
Fix issues with null/undefined references when enabling `preloadModules` for `IonicModule`

Ionic Version: 3.x

### CODE REVIEW

**Comment by soumak77** [comment]
Can this get merged?  I'm still having this issue with 3.1.

**Comment by soumak77** [comment]
@brandyscarney @manucorporat this is still broken.  Please merge or provide feedback on the changes.  Thanks.

**Comment by manucorporat** [comment]
@soumak77 i clearly see how this is an issue, I will merge it this week.

Can you add/update an unit test so this will not happen again?

**Comment by soumak77** [comment]
@manucorporat unit tests have been added

**Comment by manucorporat** [comment]
Merged! thanks a lot for the PR!

**Comment by wilgert** [comment]
Could you please create  a release from the merged commit ASAP, we can not run our unit tests because of the bug that this PR fixes.

**Pull request merged**
