### PR TITLE
Add support for trigger.io

### PR DESCRIPTION
**Pull request by sloops77**
This adds support for recognising trigger.io apps as WebView not a browser. To make this work at the moment the user needs to add this in a angular.run block:
```
window.addEventListener("load", function() {
  if (!!window.forge) {
    ionic.trigger('deviceready', {
      target: document
    });
  }
});
```

Reopens this PR cleaned off blurAll removal:  https://github.com/driftyco/ionic/pull/2667

### CODE REVIEW

**Comment by francisosih** [comment]
Hello @sloops77 I tried your suggestion and I haven't been able to make it work.

**Comment by sloops77** [comment]
Hi Francis, check the forum for my reply

**Comment by sloops77** [comment]
Perry,

thanks for merging. It would be good to integrate the fake 'deviceready'  event code into master so people dont need to discover this issue to figure out why "it isn't working". Would you suggest adding it to platform.js directly, or would it be better to have a separate triggerio.js file in utils? The benefit of the latter is that any adapter code or phonegap event triggering can be encapsulated there. 

I suppose i just convinced my help, but if i could get your ok then i'll send in the next PR this week.

**Comment by francisosih** [comment]
I would suggest adding it straight into the triggerio.js, thanks mate!

Francis


*Disclaimer:This message and any files transmitted with it, is
confidential, especially as regards personal data. It is intended solely
for the use of the individual or entity to whom it is addressed. If you are
not the intended recipient and have received this information in error or
have accessed it for any reason, please notify us of this fact by email
reply and then destroy or delete the message, refraining from any
reproduction, use, alteration, filing or communication to third parties of
this message and files on penalty of incurring legal responsibilities. The
sender does not guarantee the integrity, the accuracy, the swift delivery
or the security of this email transmission, and assumes no responsibility
for any possible damage incurred through data capture, virus incorporation
or any manipulation carried out by third parties.*

**Pull request merged**
