### PR TITLE
ion-item: Swipe Direction

### PR DESCRIPTION
**Pull request by xlozinguez**
This will allow a swipe from left to right on ionList's ionOptionButton which is very useful to mimic iOS's gesture. (Feature request from https://trello.com/c/rPzCsNlS/21-ion-item-swipe-direction)

Entirely based on @blixt 's work found at https://github.com/driftyco/ionic/pull/2948

I've rebased on the latest master branch.

Can we get guidance in order to see this merged in ionic in the near future? Thank you!

### CODE REVIEW

**Comment by mhartington** [comment]
I like this. Works really well. I don't think it will make it in for 1.0.1, but possibly for the release after that. Great job @xlozinguez and @blixt.

Thoughts @perrygovier ?

**Comment by xlozinguez** [comment]
Awesome to hear @mhartington looking forward to it!

**Comment by harked** [comment]
Hi. can you please provide the step by step how to use it in real case?
I mean sample code (i.e in codepen) to see how it work..

**Comment by xlozinguez** [comment]
sorry for the late reply @harked I am lacking time to create a demo right now but you can find instruction here: https://github.com/driftyco/ionic/pull/3948/files?diff=unified#diff-586fc43b1ace00e99916eb439c7b3792R30
You basically simply indicate the side you want the button to appear (right by default)

**Comment by blixt** [comment]
Here's an example, where the additional button is shown on the left side instead of the default (right side). As you can see, the old style option buttons (Share and Edit in this case) don't need any changes to work like before.

```html
<ion-list>
  <ion-item>
    I love kittens!
    <ion-option-button class="button-royal" side="left">Meow</ion-option-button>
    <ion-option-button class="button-positive">Share</ion-option-button>
    <ion-option-button class="button-assertive">Edit</ion-option-button>
  </ion-item>
<ion-list>
```

**Comment by mistapostle** [comment]
Hi, 
Noted this when I was working on a merge of the swipe-delete style & effect  of framework 7  , which looks more elegant . just wondering if it could be accepted, if yes I'd like to create a new pull request for it ,and, of cause will merge in this one as well. below a very rough  version just to show how it would look like

https://github.com/mistapostle/ionic/tree/f7-swipe

**Comment by joeydi** [comment]
I just want to thank @blixt and @xlozinguez for their work on this. Can't wait to see this merged into master.

**Comment by ctesene** [comment]
Any updates on this? Is this on the roadmap for 1.2 since 1.1 already landed?

**Comment by romankierzkowski** [comment]
Looking forward to see this feature in the framework. Any plans on releasing?

**Comment by mlynch** [comment]
Thanks! will review for 1.3

**Comment by danbucholtz** [comment]
Hi @blixt and @xlozinguez, if you two are game, I'm game to try to make this land in an upcoming point release on Ionic (1.3.x in theory).  We'll have to work together and get some additional tests in place, etc.  No promises, but if we work together we might be able to pull it off. Please let me know your thoughts.

Nice work, and thanks for contributing!

Thanks,
Dan

**Comment by xlozinguez** [comment]
I'm game 

Xavier mobile version

**Comment by danbucholtz** [comment]
@blixt, any interest?  We are going to need some additional tests to get this merged.

**Comment by blixt** [comment]
@danbucholtz Sorry, I submitted the initial pull request almost 20 months ago so I've forgotten most if not all context needed to work on this (also, I haven't used Ionic for well over a year now).

**Comment by xlozinguez** [comment]
@danbucholtz what do you suggest we do at this point?

**Comment by danbucholtz** [comment]
@xlozinguez,

Good question.  We need more tests in order to merge this to ensure we didn't break any other functionality.  It would be very risky to merge this as it stands now.  If you want to take a crack at it, that would be great!

Please let me know your thoughts.  I am happy to help in any way I can.

Thanks,
Da

**Comment by xlozinguez** [comment]
@danbucholtz I'm working on this during the week, I'll provide you an update by eow

**Comment by vTrip** [comment]
@xlozinguez @danbucholtz would it be too risky to include this in a current project of mine or do you think it is stable enough ?

**Comment by danbucholtz** [comment]
Hi @vTrip,

Your mileage may vary.  I haven't tested it personally.  I think it's worth a shot trying this in an app.  If it doesn't work, you can easily revert.  It's quite a bit scarier when dealing with the hundreds of thousands of Ionic apps :)  Not as easy to revert a fix if it doesn't work in some situations.

**Comment by danbucholtz** [comment]
Hi @xlozinguez,

That's awesome!  Keep me posted on how it goes.

Thanks,
Dan

**Comment by vTrip** [comment]
@danbucholtz great, I think i'll use this in a brach of my project.

I'm still learning git, so excuse the question, but how can I checkout this PR into my project ?

**Comment by vTrip** [comment]
@danbucholtz @xlozinguez happy to report I have this feature working in my app.

I had issues merging this will a working branch so I ended up manually copying/replacing the code by looking at the diff. The only issue I came across was the CSS where the option buttons were out of place. Seems as though the item-option-left/right selectors weren't being compiled into the ionic.css. 

Quick fix was to put the css code into my custom scss file which allowed it to be recognised. However I will be looking into the non-compile issue.

Working seamlessly without any lag ! Thank you for the work you guys have done on this feature, much appreciated.

**Comment by vTrip** [comment]
Found an issue: Long drags (sliding left to right) cause the ng-click event to be fired (without actually tapping the ion-option button).

**Comment by sebrojas14** [comment]
What happened with this?

**Comment by R1Daneel** [comment]
I was not able to find this issue in the `ionic-v1` repository

**Pull request closed without merging**
