### PR TITLE
chore(angular): update to 2.4.8

### PR DESCRIPTION
**Pull request by jgw96**
#### Short description of what this resolves:
Updates our Angular dependency to 2.4.8. Also updates rx and zone to what Angular 2.4.8 requires.

#### Changes proposed in this pull request:

- Update Angular to 2.4.8
- Update rxjs to 5.0.1
- Update zone.js to 0.7.2

**Ionic Version**: 2.x

**Fixes**: #10422

### CODE REVIEW

**Comment by Manduro** [comment]
The Angular dependencies are actually as below (note the semver prefixes). This resolves to `rxjs@5.2.0` and `zone.js@0.7.7`, currently. Can we have Ionic use the latest and greatest as well?

```
  "dependencies": {
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.0.1",
    "zone.js": "^0.7.2"
  }
```

Besides that, I would really love to see Ionic stop depending on fixed versions. Why not set angular at `~2.4.8` or even `^2.4.8`, like everyone else does? The stability of Angular has settled and they are extremely careful with breaking changes.

**Comment by jgw96** [comment]
Good news! Snapshot checks out 🎉  which means this is almost ready.

**Comment by mhartington** [comment]
Hi @Manduro, this is the exact opposite of what we've seen to be honest. 

For example, since angular 2.2.1 there have been breaking changes that framework/library authors need take into consideration and update.

While it would be great to just let npm and semver do it's thing and roll with it, we've seen time and time again that it doesn't always work out that way. This is why we directly pin dependencies.

**Comment by mikezks** [comment]
@mhartington, to be honest I am suprised that your mentioned breaking changes are not documented as such. (see [NG changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md))

**Comment by mhartington** [comment]
@mikezks Please re-read my comment, that is not what I said as all.

**Pull request merged**
