### PR TITLE
feat(menu): Menu opened/closed events

### PR DESCRIPTION
**Pull request by NathanWalker**
closes https://github.com/driftyco/ionic/issues/5163

### CODE REVIEW

**Comment by piotrbelina** [comment]
hello guys,
I would like to ask about this pull request. When is it going to be merged?
Cheers

**Comment by NathanWalker** [comment]
Hi @piotrbelina I'm trying to get back to it to fix up a couple things. I'll get it all set and ready this week. Thanks for the ping :+1:

**Comment by piotrbelina** [comment]
Hi @NathanWalker thanks for quick update. Great to hear. I'm trying to use https://github.com/mapsplugin/cordova-plugin-googlemaps and without menu events it is not possible to get map and menu working well

**Comment by NathanWalker** [comment]
Nice... yes I want this as well!

**Comment by NathanWalker** [comment]
@adamdbradley I have added `opened`/`closed` events. `open`/`close` were already used for the methods so didn't want to cause `duplicate identifier` issues.

I'm having trouble testing though. I unfortunately don't know the ionic v2 codebase well enough to dig further and my time is limited for trial/error session. You will see 2 different testing strategies in the test here that I'm attempting. One is with the `TestComponentBuilder` which would be a great way to test this and many of ionic's other components. This requires a `beforeEachProviders` block likely as it causes this vague error:
```
MenuController menu events should emit opened FAILED
	TypeError: queueableFn.fn.call is not a function
```
which is usually related to a provider being needed (not sure which one?)... you guys may know right away.

The other method is similar to your other specs. However this method causes problems because `nativeElement` is undefined in the Menu:
```
MenuController menu events should emit opened FAILED
	TypeError: Cannot read property 'nativeElement' of null
	    at Menu.getNativeElement (/Users/nathan/Documents/github/angular2-stuff/ionic/dist/bundles/ionic.system.js:1542:47)
	    at Menu._before (/Users/nathan/Documents/github/angular2-stuff/ionic/dist/bundles/ionic.system.js:13702:34)
	    at Menu.setOpen (/Users/nathan/Documents/github/angular2-stuff/ionic/dist/bundles/ionic.system.js:13640:30)
	    at Menu.open (/Users/nathan/Documents/github/angular2-stuff/ionic/dist/bundles/ionic.system.js:13767:37)
	    at MenuController.open (/Users/nathan/Documents/github/angular2-stuff/ionic/dist/bundles/ionic.system.js:12765:41)
	    at Object.<anonymous> (/Users/nathan/Documents/github/angular2-stuff/ionic/dist/tests/components/menu/menu.spec.js:209:26)
```

If anyone could give me insight here, I can adjust. I wish I had more time to dig further. 
This also adds `angular/testing` to the runner which will make testing components a lot better I would think. 

Additionally it would help to add some more to the `CONTRIBUTING` doc on how to run the `e2e` test suite. Looking through the `gulpfile.js` to figure it out is cumbersome and I don't see it documenting specifically unless I am really missing something.

**Comment by ciesielskico** [comment]
Hey guys, what's the status on Menu Opened and Closed events? 
Need this as well for cordova-googlemaps!

Cheers

**Comment by dusbuss** [comment]
+1

**Comment by NathanWalker** [comment]
I'll pull this back up in another day or 2 and see what I can figure out here, thanks for pinging this.

**Comment by adamdbradley** [comment]
Sorry for the late response and not merging sooner, but the code diverged enough that it was no longer a clean merge. But the opened/closed events have been added now, thanks.

**Comment by NathanWalker** [comment]
Awesome to hear, thanks @adamdbradley !

**Pull request closed without merging**
