### PR TITLE
feature : allow dynamic ion-nav-view name

### PR DESCRIPTION
**Pull request by calendee**
allow the name attribute to be evaluated as an angularjs expression

Issue #1503

Signed-off-by: Justin Noel github@calendee.com

### CODE REVIEW

**Comment by alexweber** [comment]
@brianfoody awesome, thanks for sharing!  I'm gonna give this a try when I can, looks brilliant...

**Comment by miqmago** [comment]
@brianfoody brilliant!

For me it makes sense to change `scope.$eval($attr.name)` by `$attr.name` and 
`<dynamic-nav-view name="tab"></dynamic-nav-view>` by `<dynamic-nav-view name="{{tab}}"></dynamic-nav-view>` (Hopefully it's the same!)

**Comment by Abhisht12** [comment]
I tried to write out the entire HTML by updating the text inside the $element.html() function to include the  whole segment from <ion-tabs> to </ion-tabs> and I found it works perfectly well without any issues so far. I am sure it needs a lot more testing, but if it is being initialized just once, it seems to work just fine.

**Comment by julitroalves** [comment]
Thanks guys, you help me a lot!

**Pull request closed without merging**
