### PR TITLE
(docs)Add code sample for setScrollDisabled

### PR DESCRIPTION
**Pull request by muhammedbasilsk**
#### Short description of what this resolves:
For entry level users it might be confusing to understand the usage of properties and methods.
#### Changes proposed in this pull request:

- Added a sample code to give an idea on how to use app.setScrollDisabled method

**Ionic Version**: 2.x

### CODE REVIEW

**Comment by manucorporat** [comment]
Well, this API might get removed from the docs, since the user never should use it directly.

**Comment by muhammedbasilsk** [comment]
Okay, got it.
But I saw several threads asking some ways to stop the scroll on the pages.
Hope you guys have plans for some alternatives other than css hacks :-)

**Comment by mhartington** [comment]
In addition from what @manucorporat has added, class methods should not have inline code examples as it ends up not looking great inside editors. If you want to add example for this, you can use the `@advanced` tag and place them down at the end of the docs.

See this for example
https://github.com/driftyco/ionic/blob/master/src/components/action-sheet/action-sheet.ts#L135

**Comment by muhammedbasilsk** [comment]
Sure, thanks for the suggestion @mhartington

**Comment by mtr** [comment]
So, now that `setScrollDisabled()` has been made private (`_setDisableScroll()`), what is the proper way to disable scrolling on pages?  I need to be able to do this, and used to call `setScrollDisabled()`.

**Pull request closed without merging**
