### PR TITLE
Added hasBouncing alternative to ionSlideBox.

### PR DESCRIPTION
**Pull request by danieka**
This is an implementation of the non-bouncing slide-box requested in #1172.

To keep backwards compatibility the slide-box defaults to bouncing.

### CODE REVIEW

**Comment by danieka** [comment]
Has anyone had the time to look at this? It seems like a lot of people would want this change. Also I'm more than happy to make any changes to the PR that you want.

**Comment by tomferreira** [comment]
+1

**Comment by SakyaStelios** [comment]
+1

**Comment by puurinternet** [comment]
+1 I hacked this after a long search for where and how this happened, and would like to be able to do it a nicer way.

**Comment by mlynch** [comment]
Thanks! Landed some of your commits: f617a9d181953354057879e0e54fa0a4e0aa6169

**Pull request closed without merging**
