### PR TITLE
feat(app): Better support for npm and modules manager

### PR DESCRIPTION
**Pull request by thaiat**
The purpose of this PR is to give ionic an easier integration with modules manager like `webpack` and `browserify`.

I use the same process as what was done for `angular-material`

Installation: `npm install ionic-sdk`
Usage (using webpack or browserify):
```js
var angular = require('angular');
require('ionic-sdk');
var app = angular.module('my-app', ['ionic']);
```

The nice thing is that it will now pull out the dependencies (angular-ui-router, angular-sanitze, etc...) automatically

### CODE REVIEW

**Comment by leandroz** [comment]
+1

**Comment by KNedelec** [comment]
+1

**Comment by marduke182** [comment]
+1

**Comment by Ionitron** [comment]
Greetings @thaiat!

Thank you very much from all of us on the Ionic team for submitting this pull request. We appreciate your commitment to improving Ionic. Unfortunately, we are unable to merge this particular PR, as it may cause regressions or is already out of date with regard to recent fixes. We apologize, as we know how much time you may have put into the work. 

We hope you will continue to contribute to Ionic in the future. Please note that we are more likely to merge a smaller PR that has a passing test and changes only one meaningful feature in the project. 

For more information, please review our [Pull Request Guidelines](http://ionicframework.com/contribute/#pull-request-guidelines).

Best regards,

Ionitron

**Pull request closed without merging**
