### PR TITLE
fix(input): RTL fix for input

### PR DESCRIPTION
**Pull request by sijav**
#### Short description of what this resolves:
RTL fix for input

#### Changes proposed in this pull request:
- fix padding and margin for RTL on input component

**Ionic Version**: 2.x / 3.x

**Fixes**: #11211

### CODE REVIEW

**Comment by AmitMY** [comment]
@sijav Now that the big one is merged, can you please remove all references to `padding`, `margin`, `left`, and `right`? just keep the arrow flipped.

**Comment by sijav** [comment]
@AmitMY keep the arrow flipped? the only thing changed here was padding, margin, left, and right nothing else ...

**Comment by AmitMY** [comment]
@sijav oh oops, my bad.. I had all of your PRs open and I commented on the wrong one.
I meant here:
https://github.com/driftyco/ionic/pull/11329

You can close this PR, as it is done here - https://github.com/driftyco/ionic/pull/11342 - and merged.
Some fixes for 11342 that relate to this one, like overridden properties are suggested here - https://github.com/driftyco/ionic/pull/11635

**Comment by sijav** [comment]
Closing this pr in favor of [#11342](https://github.com/driftyco/ionic/pull/11342)

**Pull request closed without merging**
