### PR TITLE
Make ionRefresher promise-friendly

### PR DESCRIPTION
**Pull request by beauby**
Make `ionRefresher` play ball when `onRefresh` function returns a promise.

### CODE REVIEW

**Comment by mhartington** [comment]
Do you have an example for how this change PTR? Also, could you provide a test for this?

**Comment by beauby** [comment]
Here is an example:
```
var myRefreshFunction = function() {
  return fetchNewData();
};
```
instead of
```
var myRefreshFunction = function() {
  fetchNewData().finally(function() {
    $scope.$broadcast('scroll.refreshComplete');
  });
};
```
Note that this commit PR is backwards compatible. I will also provide some tests.

**Comment by marksomnian** [comment]
:+1:

**Comment by ryanlin1986** [comment]
This is really good.

**Comment by mhartington** [comment]
I'll let @perrygovier take a look at this.

**Comment by beauby** [comment]
Any feedback on this one?

**Comment by mlynch** [comment]
:+1: :pizza: :beers:

**Pull request merged**
