### PR TITLE
fix(tap): on iOS9, isElementTapDisabled fails to detect data-tap-disabled attribute after few clicks (fix #4506)

### LINKED ISSUE #4506: bug: Maps and marker clicks on iOS 9
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>native hybrid app</span>

<span ionic-description>Hello,

I am directly copying/pasting a post from ionic forum (http://bit.ly/1G94nkr) as it perfectly describes the issue:

> After updating my device to iOS 9, I am having problems with detecting marker click events on maps, which was working perfectly when my device was on iOS 8. The clicks are detected at first, but after some events are performed, clicks no longer fire.

> I have tried both Google Maps and Leaflet. While I have not yet found a fully deterministic path to reproducing precisely at what point do the marker clicks no longer fire, I have noticed some patterns:

> - On Google Maps, the first 4-6 clicks are detected, and none thereafter.
> - On Leaflet, all clicks are detected in the first instance of the map view. When moving into another view and back into the map view, the clicks no longer fire. Usually 2 or 3 iterations of cycling out and in of the map view is needed before the clicks stop firing. Double clicks and other events are unaffected.
The map is always wrapped with data-tap-disabled="true".

> Is anyone else having similar problems?

Here is another post describing the issue (http://bit.ly/1LgshYe) with a codepen available (http://codepen.io/ionic/pen/uzngt).</span>

<span is-issue-template></span>

### PR DESCRIPTION
**Pull request by MarcBT**
Hi,
I have tried several workarounds to try to fix the (strange) #4506 bug.
The proposed PR seems to solve it (at least in my case).
Please, can you review it and confirm that it works on your own ?
Thanks in advance and let me know if you need more info and/or changes are required.

### CODE REVIEW

**Comment by MarcBT** [comment]
Commit amended to fix esLint errors.

**Comment by mlynch** [comment]
Closing since I think this is a duplicate of #4589. Did that fix work for you?

**Comment by MarcBT** [comment]
Hi @mlynch.
Will have a look on the fix and come back quickly to let you know if it solves the initial issue described in #4506.

**Comment by MarcBT** [comment]
Hi @mlynch, upgraded our app to ionic@1.2.4. I confirm that it does not solve the issue. Can you reconsider this please ?

**Pull request closed without merging**
