### PR TITLE
Updating dgeni pkg to 0.16.0

### PR DESCRIPTION
**Pull request by dennybiasiolli**
#### Short description of what this resolves:

This resolves issue #9028 

#### Changes proposed in this pull request:

- updating dgeni-packages step-by-step to test every single update and resolve eventual problems
- (if merge will be accepted, I can squash commits and reword)

**Ionic Version**: 2.x

**Fixes**: #9028

### CODE REVIEW

**Comment by perrygovier** [comment]
LGTM, but can you get rid of the random change to `src/components/item/item-reorder.ts`?

**Comment by mhartington** [comment]
Hmm that item-reorder change just looks like a stray empty line. Maybe not worth worrying about.
Either way, we can apply this locally and make the change here and there if you want @perrygovier

**Comment by dennybiasiolli** [comment]
@perrygovier @mhartington empty line removed ;)

**Comment by perrygovier** [comment]
Thanks. When we run this, a lot of previously private/ignored pages and classes show up. Are you able to modify it so that the output is identical to before the update?

**Comment by dennybiasiolli** [comment]
Yes I will try, but before PR I've tryed on master and than on branch and I didn't spot differences. The command to launch is "gulp docs" right?

**Comment by dennybiasiolli** [comment]
@perrygovier you are right, it starts to differ in _includes/v2_fluid/api_menu_flat_nightly.html with dgeni-packages v0.12.0 or greater. Tomorrow morning I will investigate better about this.

**Comment by dennybiasiolli** [comment]
@perrygovier: with commits

- docs: getJsDocTags function added to readTypeScriptModules
- docs: using getJsDocTags function in createExportDoc
- docs: using jsDocTags to ignore private modules

the exports of classes marked as
```
/**
 * @private
 */
export class ClassName { /* ... */ }
```

doesn't appear in _includes/v2_fluid/api_menu_flat_nightly.html, but other exports like this
```
/**
 * @private
 */
export const ConfigToken = new OpaqueToken('USERCONFIG');
```
continues to appear.

Any other ideas?
Now I'll continue working on a solution to avoid showing of those pages:
- ConfigToken
- DeepLink
- DeepLinkConfigToken
- DocLangToken
- DocumentDirToken
- IONIC_DIRECTIVES
- isActivatable
- NavigatorPlatformToken
- UrlToken
- UserAgentToken

**Comment by dennybiasiolli** [comment]
@perrygovier you can check now, it seems to have the same output as master branch. Thanks for your patience

**Comment by perrygovier** [comment]
Merged with 217c171e5fa26793c014008c3a29418399e508e3

Thanks! This allows us to use some new Dgeni features in the near future too.

**Comment by dennybiasiolli** [comment]
Thanks to you @perrygovier , now I'm PR-ing dgeni-packages repository to add the same resolution to the original package, so in future you can use directly that package instead of the custom one.
;)

**Pull request closed without merging**
