### PR TITLE
fix(toast): allow input focus while toast is visible

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Keyboard focus is trapped when the toast overlay is active. This prevents focusing form controls on the view. 

Issue Number: #24571

## What is the new behavior?

Keyboard focus is not trapped for overlays presented for `IonToast`. 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by amandaesmith3** [comment]
I found a few comments in `src/utils/overlays.ts` mentioning that toast should be excluded from focus trapping, so it does seem this change is how it's supposed to be; I have to wonder how it regressed 🤔 I had a couple questions about how this interacts with screen readers:

1. What about toasts that don't have a duration, remaining on screen until manually dismissed? Should focus trapping be maintained for those?
2. Does this change prevent screen readers from announcing the toast when it appears?

**Comment by sean-perkins** [comment]
Agreed! I saw the same comments (#21716) and will do a further dive to see if I can find the exact regression. I know we have a few other issues around forcing the focus trap on overlays and some developers have asked for more direct access to toggling that behavior. This change currently is an internal API to configure that option, that would eventually allow us to support a binding on the overlay components to disable focus trap (for specific needs).

Currently, I believe this PR direction may be ideal regardless of the point of regression, as we were likely always adding a focus listener on the toast, instead of conditionally applying that logic for overlays that actually need it.

**Comment by sean-perkins** [comment]
I still need to verify screen reader behavior, on my list for early tomorrow!

**Review by liamdebeasi — APPROVED** [review]

**Comment by sean-perkins** [comment]
@amandaesmith3 verified with VO on mac, the toast is still announced correctly either before you input text, or after typing and opening a toast.

**Review by amandaesmith3 — APPROVED** [review]
Awesome, thanks for checking on that 👍

**Pull request merged**
