### PR TITLE
fix(viewSwitcher): greatly improved perceived performance by using ionic.requestAnimationFrame

### PR DESCRIPTION
**Pull request by andreialecu**
This improves perceived performance, especially on Android, and fixes
https://github.com/driftyco/ionic/issues/3907

### CODE REVIEW

**Comment by chooseapp** [comment]
It is working really well. Hope this will be merged soon

**Comment by ispieter** [comment]
+1

**Comment by mlynch** [comment]
Thanks, I did some testing and it seems to work fine. Marking for further testing with Android and Windows before release

**Comment by luco** [comment]
Thanks a lot @andreialecu! Worked perfectly!

**Comment by chooseapp** [comment]
@luco Take care, it brokes the ionic back button

**Comment by daltonpereira** [comment]
@andreialecu  Hey It worked. but it flickers for the first tab tap

**Pull request merged**
