### PR TITLE
feat(slides): swiper controller

### PR DESCRIPTION
**Pull request by Manduro**
#### Short description of what this resolves:
Adds functionality to Slides that was lost in the porting.

#### Changes proposed in this pull request:

- Adds Swiper's Controller, which can be used to have one Swiper control another. (Ported from https://github.com/nolimits4web/Swiper/blob/master/src/js/controller.js)

**Ionic Version**: 2.0.0-rc.5

**Related**: #9933

### CODE REVIEW

**Comment by brandyscarney** [comment]
Thanks! :)

**Comment by Manduro** [comment]
@brandyscarney Thank *you* for the awesome framework! Would love a nightly with this ;)

**Comment by brandyscarney** [comment]
@Manduro Sorry, we recently added `noImplicitAny: true` to the framework so I had to fix some issues with that. :) Nightly: `ionic-angular@2.0.0-rc.5-201701121905`

**Comment by Manduro** [comment]
Awesome!

**Pull request merged**
