### PR TITLE
Add support for trigger.io

### PR DESCRIPTION
**Pull request by sloops77**
This adds support for recognising trigger.io apps as WebView not a browser. To make this work at the moment the user needs to add this in a angular.run block:
```
window.addEventListener("load", function() {
  if (!!window.forge) {
    ionic.trigger('deviceready', {
      target: document
    });
  }
});
```

### CODE REVIEW

**Comment by adamdbradley** [comment]
Why did you remove the blurAll calls?

**Comment by adamdbradley** [comment]
I think we can add in the trigger.io support, but need to test removing blurAll() (there's other issues with blurAll(), so want to take our time removing those). @mhartington would you be able to get the trigger.io support in?

**Comment by mhartington** [comment]
Curious about the `blurAll()`calls as well. Care to explain @sloops77?

**Comment by sloops77** [comment]
Hi guys,
I'm sorry that removal shouldnt have been included in the PR. The reason for the removal was a separate issue that you guys have already dealt with. https://github.com/driftyco/ionic/issues/2801.

**Comment by sloops77** [comment]
I'm closing this one and reopening in light of you guys already removing blurAll after beta14 was released

**Pull request closed without merging**
