### PR TITLE
feat(slidebox): Add a callback for valid swipe that encountered resistance because reached the bound and not looping

### PR DESCRIPTION
**Pull request by sunshineo**
This callback is particular useful to me. I use the slidebox for the tutorial of my app. Unlike the demo, my tutorial is full screen. I do not have place for a button saying "Start using my app". So when user swipe the last slide of the tutorial, they start to use the app. I have observed this behavior in many apps.
My previous pull request was not properly implemented https://github.com/driftyco/ionic/pull/2710 . I had to save the delta.x for before the resistance take effect and then decide if I should fire the callback when an invalid swipe was made.

### CODE REVIEW

**Comment by sunshineo** [comment]
Happy New Year! Can this be merged?

**Comment by perrygovier** [comment]
Can you provide an example of what this fixes and add unit tests?

**Comment by sunshineo** [comment]
This does not fixes anything. This is a new feature as indicated by the title.
The use case is that a lot of apps tutorial exist when you slide the last slide and user start to use the app.
I do not have time to provide any unit tests.

**Comment by sunshineo** [comment]
Any word on this?

**Comment by mhartington** [comment]
Closing this since there is no unit test included and the PR is rather old.

**Pull request closed without merging**
