### PR TITLE
fix(navcontroller): lazy loading is queued (WIP)

### PR DESCRIPTION
**Pull request by manucorporat**
WIP

DO NOT MERGE!

### CODE REVIEW

**Comment by mburger81** [comment]
Hi,  how is the situation about this bug? I think this is a really severe bug and it would be nice to have a status update on this bug and if you would integrate it on 3.1 or if it would be testable on a nightly?

**Comment by manucorporat** [comment]
@mburger81 we might merge it tomorrow

**Comment by mburger81** [comment]
@manucorporat I upgraded to last nightly, where one of the issue I opened was closed. But now there are other problems. Problems like this:

Runtime Error
```
Uncaught (in promise): invalid views to insert
Stack
Error: Uncaught (in promise): invalid views to insert
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at l (http://localhost:8100/build/polyfills.js:3:6251)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:5607)
    at NavControllerBase._failed (http://localhost:8100/build/main.js:47536:16)
    at http://localhost:8100/build/main.js:47579:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14529)
    at Object.onInvoke (http://localhost:8100/build/main.js:4499:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14469)
    at n.run (http://localhost:8100/build/polyfills.js:3:9741)
    at http://localhost:8100/build/polyfills.js:3:6774
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15213)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:4490:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15134)
    at n.runTask (http://localhost:8100/build/polyfills.js:3:10390)
    at a (http://localhost:8100/build/polyfills.js:3:5313)
```

**Comment by manucorporat** [comment]
@mburger81 are you trying to insert one null/undefined view?

**Comment by mburger81** [comment]
@manucorporat Honestly I'm not sure what do you intend with null/undefined view. If you intend not invalid PageNames for `IonicPage`s, I'm sure I'm not doing this. I use the same navigation as and pages as I use on `ionic-angular@3.0.1`  I only upgrade to nightly version where you have merged yesterday your PR. 

So it should work out of the box.

The other issue I recognized after upgrade is this:
a) run `ionic serve`
b) open browser and navigate to `http://localhost:8100/` where my login page is loaded as expected
c) I authenticate to the server and where redirected to main PAGE
d) open a new tab in my browser and load the same URL as before, where my login PAGE should redirect me to the MAIN page because I'm already logged in. But nothing is happening. no error or something else.

So same code, different result. I have to check my code and debug what is now different.

One thing to know is:

We have a multilevel navigation, in my `app.component.ts (MyApp Page)` we have one `ion-nav`
`<ion-nav [root]="rootPage" swipeBackEnabled="false"></ion-nav>`
On constructor we set the `rootPage` to your `LoginPage`

So now the `LoginPage` has an `ionViewCanEnter`
```
ionViewCanEnter(): Promise<any> {
        return this.authGuard.canActivateLoginPage();
}
```
This checks if user is already logged in, if it is already logged in we load the `MainPage` which is our main page for all the other pages, with sidemenu and others.

In this MainPage we have the second `ion-nav` where we load always the other pages, like `UserManagementPage` and so on.
```
</ion-menu>

<!-- Disable swipe-to-go-back because it's poor UX to combine STGB with side menus -->
<ion-nav #content swipeBackEnabled="false"></ion-nav>
```

Every page checks in `ionViewCanEnter` if user is still authenticate, and if not or if some http request get `401` status we will redirect APP's ion-nav to login page.
```
constructor(private appCtr: App, private http: Http) {}
...
this.appCtr.getRootNav().setRoot('LoginPage');
```

I hope I explained it well and you can understand what we are trying to do.

We are also not sure if this is the right implementation of what we need to do.
We asked help on ionic forum some weeks ago, but no response, in the blog we referenced @mhartington example for `star-track-ionic` which has also a two level navigation
https://forum.ionicframework.com/t/ionic3-with-ionicpage-and-two-different-router-levels/85595
https://github.com/mhartington/star-track-ionic

**Comment by mburger81** [comment]
Ok I checked for the second issue.

I can not `setRoot` for my root ion-nav to load `MainPage` if user is already logged in.

`this.appCtr.getRootNav().setRoot('MainPage');`

But there is no error or something else for that, also `MainPage` is not loaded as requested

**Comment by mburger81** [comment]
We tested 3.0.1-201704201450 (nightly) and both of the bugs persists.

**Pull request merged**
