### PR TITLE
Adding a more complete Swiper definition file

### PR DESCRIPTION
**Pull request by dudeofawesome**
#### Short description of what this resolves:

The current definition file for Swiper is very incomplete. I've fixed that
#### Changes proposed in this pull request:

Adding a more complete Swiper definition file

**Ionic Version**: 2.x

**Fixes**: No open issues. I was going to open one, and then decided to just fix it myself.

### CODE REVIEW

**Comment by HendrikGrobler** [comment]
This fixes part of: #7581

**Comment by ramonornela** [comment]
Fix with typings and npm is best ;)

**Comment by caleuanhopkins** [comment]
is there any chance of getting this merged into the next update for beta? The current docs say `getSlider()` returns a `Swiper` instance but right now it's not allowing the use of any callbacks. I've had to copy and paste this update to `swiper-widget.d.ts` file in my local `node_modules` to finally be able to query the `Swiper` instance with the API outlined on the Swiper website.

**Comment by dudeofawesome** [comment]
I'd like to put it up on Typings, but I can't seem to find any information about publishing it there.

Once it is there, then Ionic can import it instead of including the actual `.d.ts` file

**Comment by brandyscarney** [comment]
I'm going to close this as slides have since been refactored, but thank you! :)

**Pull request closed without merging**
