### PR TITLE
docs(infinite-scroll): use proper equality check

### PR DESCRIPTION
**Pull request by matzar**
Changed '==' to '===' in [infinite-scroll](https://ionicframework.com/docs/api/infinite-scroll) readme.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Lint (`npm run lint`) has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Updated documentation so people don't get scared when seeing '==' equality.

Issue Number: # 

## What is the new behavior?

Changed '==' to '===' in [infinite-scroll](https://ionicframework.com/docs/api/infinite-scroll) [Usage](https://ionicframework.com/docs/api/infinite-scroll) code example.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by matzar — COMMENTED** [review]
Double checked everything - 5 occurences of double-equals have been replaced with tripple-equals.

**Comment by amandaesmith3** [comment]
Thanks for the PR! The readme file you've updated is mostly auto-generated (everything below the `<!-- Auto Generated Below -->` comment) and will be overwritten when `build` is run. The source files for the usage examples are under `infinite-scroll/usage`. Could you update those instead, and then run `npm run build` to propagate the changes to the auto-generated files (and commit those updates as well)?

**Review by amandaesmith3 — APPROVED** [review]
Thanks! This LGTM once tests pass and Sean has a chance to take another look.

**Review by liamdebeasi — CHANGES_REQUESTED** [review]
Can we remove the package-lock changes?

**Comment by matzar** [comment]
> Can we remove the package-lock changes?

Now, I've commited only `infinite-scroll/usage` changes and built `readme`. No `package-lock.json`s or `api.txt`.

**Review by liamdebeasi — APPROVED** [review]

**Pull request merged**
