### PR TITLE
Update navBarDelegate to support bar appearance changes

### PR DESCRIPTION
**Pull request by alvarowolfx**
When I was developing a app I needed to change the navbar color depending on the screen. I tried using the rootScope workaround just like on issue #2732 but it didn't worked out because the navbar does not sync with it's inner headerBar. 

Besides that I feeled that this was not the best way to do this. I already develop native iOS apps and the navbar has methods to change it's appearance, that why I thought that the best solution is to add the ```appearance``` method to change it.

### CODE REVIEW

**Comment by mhartington** [comment]
Thanks for this! 
Marking this for 1.1 as it would be a breaking change.

**Comment by lonormaly** [comment]
+1

**Comment by felquis** [comment]
+1

**Comment by gyf304** [comment]
Urgently need this

**Comment by Orthocenter** [comment]
+1

**Comment by zoehneto** [comment]
Is there an update on when this will be merged?

**Comment by danbucholtz** [comment]
Hi @alvarowolfx, nice work!  Thanks for contributing to Ionic.  I will work with the team to see what we can do about getting this into an upcoming point release on Ionic.  We'll be in touch.

Thanks again for contributing.

Thanks,
Dan

**Comment by mbalanka** [comment]
It would be nice to get an update on this.

**Pull request closed without merging**
