### PR TITLE
WIP: slidebox

### PR DESCRIPTION
**Pull request by ajoslin**
Test is in test/html/slidebox.html

Benefits of refactor:
- Only current, previous, and next element are ever in the DOM
- Only the scope of the current element is ever connected to $watches, events, etc
- Abstraction of swiping between elements is open for tabs with almost no work, and also sidemenu and views with a bit of work.

TODO
- [x] Lower the transitionDuration depending on user's drag velocity.
- [x] Finish documentation
- [x] Fix CSS height problem
- [x] Unit test utils/list
- [x] Cover case with only two slides and previous

### CODE REVIEW

**Comment by bjammin** [comment]
So this never made it into 1.0 ?

**Comment by bjammin** [comment]
Yes that's especially what I'm interested in @subeebot 

I have a large slidebox and sometimes I transition to the view and slide to (for example) slide 100.  Unfortunately it loads slides 1-99 as well resulting in a large delay.   I'd love to see "Only current, previous, and next element are ever in the DOM" but it seems this pull request was never accepted :(

**Comment by marcsyp** [comment]
Yeah, I'm still dealing with huge load times that make my app appear
amateurish. :(

On Wed, May 27, 2015 at 11:58 PM, bjammin <notifications@github.com> wrote:

> Yes that's especially what I'm interested in @subeebot
> <https://github.com/subeebot>
>
> I have a large slidebox and sometimes I transition to the view and slide
> to (for example) slide 100. Unfortunately it loads slides 1-99 as well
> resulting in a large delay. I'd love to see "Only current, previous, and
> next element are ever in the DOM" but it seems this pull request was never
> accepted :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic/pull/2288#issuecomment-106201086>.
>



-- 
Marc Syp, Creative Technologist
San Francisco, CA

WARNING: The information contained in this message is legally
privileged and proprietary information intended only for the use of
the individual or entity named above. If the reader of this message is
not the intended recipient, you are hereby notified that any
dissemination, distribution, or copy of this message is strictly
prohibited. If you have received this message in error, please
immediately delete the original message and notify the sender.
Communication of the information contained in this message to any
unauthorized persons may be a violation of state or federal laws.

**Comment by bjammin** [comment]
I did find this post:
http://forum.ionicframework.com/t/what-should-i-do-if-i-want-to-show-thousands-of-pages-in-a-slide-box/14092

It discusses some methods (code included) to implement your own lazy loading.  I'll be going down this path I guess.

**Comment by marcsyp** [comment]
Thank you for that!  Will give it a try when I have a chance and report
back here.

Marc


On Thu, May 28, 2015 at 5:05 PM, bjammin <notifications@github.com> wrote:

> I did find this post:
>
> http://forum.ionicframework.com/t/what-should-i-do-if-i-want-to-show-thousands-of-pages-in-a-slide-box/14092
>
> It discusses some methods (code included) to implement your own lazy
> loading. I'll be going down this path I guess.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic/pull/2288#issuecomment-106634629>.
>



-- 
Marc Syp, Creative Technologist
San Francisco, CA

WARNING: The information contained in this message is legally
privileged and proprietary information intended only for the use of
the individual or entity named above. If the reader of this message is
not the intended recipient, you are hereby notified that any
dissemination, distribution, or copy of this message is strictly
prohibited. If you have received this message in error, please
immediately delete the original message and notify the sender.
Communication of the information contained in this message to any
unauthorized persons may be a violation of state or federal laws.

**Comment by bjammin** [comment]
I was trying to use slidebox to re-create this image carousel as pure ionic:
https://blueimp.github.io/Gallery/

Unfortunately I haven't been able to get near the performance of that component, even with a small number of slides.  So I have been forced to adapt blueimp instead.  It's a bit messy with no direct binding but I have managed to work around it and the performance is streets ahead of slidebox.

I guess slidebox is trying to cope with a lot of different use cases so it's not as well optimised as an image carousel.

**Comment by vandervidi** [comment]
Is there any working solution for lazy loading of slides?

**Comment by 5amfung** [comment]
Any update on this?

**Pull request closed without merging**
