### PR TITLE
Allow options buttons on both sides

### PR DESCRIPTION
**Pull request by blixt**
This is a resubmit of pull request #2111 with updates to work with the latest master of Ionic. I've since added a test, and if anything else is lacking I would appreciate some support in getting this merged this time around.

### CODE REVIEW

**Comment by tannerlinsley** [comment]
+1

**Comment by blixt** [comment]
Sorry, I just revisited this pull request and `master` has drifted too much for me to fix this. I tried to submit this twice in the past but it has been ignored for almost 10 months now, so this work is lost.

**Comment by xlozinguez** [comment]
:cry:

**Comment by xlozinguez** [comment]
@blixt I've rebased your changes onto master and it still works properly for my project... hopefully we can get this merged! :+1:

**Pull request closed without merging**
