### PR TITLE
fix(rtl): menu

### PR DESCRIPTION
**Pull request by AmitMY**
#### Short description of what this resolves:
- Having `[side]="exp"` on `ion-menu` now updates the slide gesture in real time
- Menu when switching to RTL or to LTR in runtime
- Menu sides now include: `'left' | 'right' | 'start' | 'end'`

##### Menu
- For the `slide-edge-gesture` I added a method `setEdges` to update the edges whenever needed.
- Menu now implements angular lifecycle interfaces.
- Changed `side` input to `get/set`

##### Swipe-back
- For platform, I added an event emitter `dirChanged`, that emits whenever you call `.setDir`
- Then, from `swipe-back`, I initialised the slide using current dir, and added a subscriber for when dir changes. 

##### Tests
- should get the only left menu on start ltr
- should get the only left menu on end rtl
- should get the only right menu on end ltr
- should get the only right menu on start rtl
- should switch menu side in runtime
- should switch menu side in runtime by direction

**Ionic Version**:  3.x

This PR makes https://github.com/driftyco/ionic/pull/11190 obsolete. 

All tests (including new ones) passed

### CODE REVIEW

**Comment by AmitMY** [comment]
@brandyscarney Ready and passing. Can you review?

**Comment by AmitMY** [comment]
@John-Luke Can you have a look to see if I am missing something for the menu / tests?
@manucorporat Is this PR ok? (it takes the right stuff from old one and adds on them)

And anyone who can help - This was tested only via code tests. Is there a way to see this in a real app somewhere?

**Comment by manucorporat** [comment]
@AmitMY I will merge this + some changes
I don't think it is a good idea to support runtime dir change. how is that useful? and implementing correctly is complicated and error prone, take a look at menu-types, you have not been any change there, and it will require some in order to work properly with RTL changes at runtime

**Comment by manucorporat** [comment]
@AmitMY I mess up with git, looks like `git merger --squash` removed you as author... I am sorry about that, just noticed when pushed the changes

**Comment by AmitMY** [comment]
@manucorporat No problem :) Glad it got merged
I was just about to push some menu-types changes as you suggested, but still testing

Thanks for the merge!

**Comment by manucorporat** [comment]
well, I would wait for the runtime change of dir. Probably something we should look at it once RTL is working properly in ionic, do not focus on that just yet.

Also, I don't want to add more complexity if the change does not bring any value, is it possible in a real app to change the direction?

**Comment by AmitMY** [comment]
@manucorporat Runtime partially shelved.
Because apps - like mine - offer the ability to change the app's language within settings, there is a change to `dir`, which means there is a change to `side` which ultimately mean that there should be runtime changes.

So now there is better support, but not the final version.
I added support for the realtime direction change for menu-types, but I can't make tests to pass. I will create a different PR where we will discuss it.

**Comment by AmitMY** [comment]
@manucorporat Also, small request - because I don't seem to be able to, can you please add `rtl` tags for all of the rtl PRs? Much easier to track them that way :)

**Pull request closed without merging**
