### PR TITLE
chore(changelog): recommend latest version of storage

### PR DESCRIPTION
**Pull request by jgw96**
#### Short description of what this resolves:
ionic storage 1.1.6 had an issue that caused a white screen for some users. Ionic storage 1.1.7 fixed this and this change updates our rc4 changelog to recommend updating to 1.1.7 . https://github.com/driftyco/ionic/issues/9677

#### Changes proposed in this pull request:

- update version of ionic storage we recommend users updating too

**Ionic Version**: 2.x

**Fixes**: #9677

### CODE REVIEW

**Comment by ahmedalmulki** [comment]
Hi what about Ionic 3 with ionic storage 2.0.1 , I have same problem white screen after splash screen ?

**Comment by yemenifree** [comment]
@ahmedalmulki I use the same version of ionic & ionic storage without any problem, make sure you hide `splash screen` manually after app be ready 

```js
this.platform.ready().then(() => {
      this.splashScreen.hide();
});
```

Then disable auto hide splash from `config.xml` 

```xml
<preference name="FadeSplashScreen" value="false" />
<preference name="AutoHideSplashScreen" value="false" />
```

**Comment by ahmedalmulki** [comment]
@yemenifree  Thanks yemenifree , its work now but the splash screen take too time to disappears , is there any way to let ionic app start up more faster ?

**Comment by Sampath-Lokuge** [comment]
@ahmedalmulki  Use this `ionic cordova build android --prod`

**Pull request merged**
