### PR TITLE
feat(toast): add toast component

### PR DESCRIPTION
**Pull request by dmackerman**
#### Short description of what this resolves:
Adds a new Toast component.

iOS | Android | Windows
------------ | ------------- | -------------
toast | toast-md | toast-wp

#### Changes proposed in this pull request:

- added new `Toast` component
- added new `Toast` docs

##### TODO:
- [ ] clean up docs
- [x] add Windows platform 
- [ ] remove errant code
- [ ] add tests

**Ionic Version**: 2.x

**Fixes**: #5582

### CODE REVIEW

**Comment by Luchillo** [comment]
Hi, i'm digging in your code and that's a lot of work there, i see you subclass from `ViewController`, does that mean it has it's own instance and therefore it's isolated of the main app `ViewController`?

You see, i have quite a long history with Ionic 2 Alerts (was named popups back then in alpha.42) and in the current state it breaks if you open more than 2 Alerts at the same time due to time between transitions, what would happen to this component if i open a toast notification twice before closing the first one? what about with an Alert and a toast together? does it work ok? or am i misunderstanding the purpose of the `ViewController`?

**Comment by Luchillo** [comment]
After watching the gifs up the PR i think you block the toast until the current one closes, is it a side effect of subClassing the `ViewController` or is it an intended behaviour.

**Comment by dmackerman** [comment]
@Luchillo The reason I extended `ViewController` is because it seemed to be the pattern used for pushing components over the existing view with the `present` method. It's used in `Modal`, and `ActionSheet` as well - but I do think for Toasts there is a little bit of unique behavior in terms of multiple toasts being on screen at the same time, which is currently not possible.

If we wanted to support multiple toasts on screen at once, I think a new approach is needed, or an extension of the ViewController to manage them. Just kinda depends on what the drifty folks think. :)

**Comment by Luchillo** [comment]
I don't think it should need to support multiple toast notification, maybe just a queue, but stacking up toast notification that will likely be dismissed with timeouts will not be beneficial at all since the time between the first one to close and the consequent ones could be too short for an user to read.

Anyway i asked about the opening and closing because the Alert component uses a similar mechanic by being presented to the `NavController` currently active, that generates errors when you try to open multiple ones or the user opens them by accident, almost always if you don't manage the multiple opened Alerts scenario the app breaks horribly forcing the user to close and re-open the app, i wan't to avoid that kind of scenario in your component, learn from the history of the Alert component.

Tough you seem to have that covered as you block the toast notification so if the user triggers more than one at any given time it will not work, i think it's a good behavior, if i were to improve anything would be to queue the notifications so that they don't stack up, with the alpha.42 popups stacking where feasible since they were dismissed by clicks, but as the main function of toast is short messages that time out, stacking is not an option.

**Comment by jgw96** [comment]
Hey @Luchillo ! If im understanding correctly you would like to have multiple alerts open at the same time correct? If so, what is the use case behind having multiple alerts open at the same time? Thanks for being so active with Ionic!

**Comment by Luchillo** [comment]
It was a workaround since i was using the alert for replacement for a 'loading indicator', since http request take sometimes close to 0 ms and some times up to 10 sec (and that is with a timeout), the transitions were fast and trying to close the first popup in alpha.42 resulted in both or none being closed.

So the workaround was to let the popups stack and close all with references stored to those popups when user clicked in the close or ok or cancel button.

**Comment by Luchillo** [comment]
When using Alerts right now, if the popup shown depends on non user triggers like http request it could result in multiple alerts being opened leading to breaking navigation, i have posted multiple issues about it in the past, some of them unsolved due to the purpose intended for Alerts.

**Comment by jgw96** [comment]
@Luchillo thanks for explaining your use case! I think I may have a solutionfor your loading indicators that may work better for you than using alerts. Ill post tonight once I do some testing to make sure it will work. Thanks again! (:

**Comment by Luchillo** [comment]
@jgw96 dont worry about it, i made my own and works great, i actually made my own gist for it:
https://gist.github.com/Luchillo/fc3d01f29580d5067541

**Comment by jgw96** [comment]
@luchillo just checked it out, awesome work! Just a heads up I see you're using the Ionic/Ionic package still which has been changed to Ionic/Angular.

**Comment by Luchillo** [comment]
Noted, i will check that out soon.

2016-03-23 11:05 GMT-05:00 Justin Willis <notifications@github.com>:

> @luchillo <https://github.com/luchillo> just checked it out, awesome
> work! Just a heads up I see you're using the Ionic/Ionic package still
> which has been changed to Ionic/Angular.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic/pull/5906#issuecomment-200412539>
>



-- 
Carlos López

Ingeniero Desarrollador
Programador Full Stack

Skype: luchillo.lopez

Móvil: +57 305 295 3543
Medellín, Colombia

**Comment by brandyscarney** [comment]
Thanks so much for the PR. :smile:

**Pull request merged**
