### PR TITLE
Fix for issue #3004 - bug:  show/hide causes event handler leak

### PR DESCRIPTION
**Pull request by hravnx**
Here by a fix for issue #3004.

The fix is fairly straightforward - when adding the resize event handler, simply use a named function instead of an anonymous, so that it can be referenced when removing the event handler again.

### CODE REVIEW

**Comment by perrygovier** [comment]
Can you get rid of the line removing the resize trigger? That's being taken care of in another commit.

**Comment by hravnx** [comment]
Hi Perry,

Sorry for not responding sooner, but I've been fairly busy and I'm not
using Ionic anymore, so other things have taken precedence.

I just tried to push the change you asked for, but apparently Github is
still being attacked or is unstable ... in any case, pushing fails with
connection failure messages.

I will try later, but otherwise, feel free to just copy the code into
another commit, I don't really need credit for this :-)

be well
-h-

**Comment by szuzul** [comment]
Hi is this in relation with popover directive also and  [#3463](https://github.com/driftyco/ionic/issues/3463)

**Comment by mlynch** [comment]
Closing since this is stale

**Pull request closed without merging**
