### PR TITLE
 .

### PR DESCRIPTION
**Pull request by leefernandes**

### CODE REVIEW

**Comment by Purus** [comment]
+1

This would be a great addition too to Ionic. I am looking for this in my current project.

**Comment by mebibou** [comment]
:+1:

**Comment by Tumne** [comment]
+1million

**Comment by jamhall** [comment]
Any reason why this has not yet been integrated? It's a great addition!

**Comment by mtpultz** [comment]
@ajoslin Is this still undergoing active architecture or development?

**Comment by GYF1** [comment]
Currently I use the popover for the drop down menu function, but it looks not so good on android. 

Hope drop down menu function comes soon. MANY THANKS for the great work, really like Ionic :+1:

**Pull request closed without merging**
