### PR TITLE
fix(menu): fix z-index issue

### PR DESCRIPTION
**Pull request by michaelgeorgeattard**
#### Short description of what this resolves:

When setRoot is called with options.direction === "back" (default), the zIndex of the view is reduced by 1. When the zIndex reaches -1, this is reset to 100.

However a zIndex of 0 breaks the application by hiding the view.

Can be replicated on http://ionicframework.com/docs/v2/components/#menus.

#### Changes proposed in this pull request:

- Z-index should be reset when it's less than 1 instead of less than 0.

**Ionic Version**: 2.x

zindex bug

### CODE REVIEW

**Comment by brandyscarney** [comment]
I'm not able to reproduce this in the demo in the docs. Are you still seeing this issue?

**Comment by michaelgeorgeattard** [comment]
Yes I just replicated on Chrome 52.

**Comment by michaelgeorgeattard** [comment]
Replicated on latest Firefox.

Steps:

- Click on Toggle Menu to open menu.
- Click on Home.
- Repeat steps above for ~100 times until z-index is 0 and page breaks.

**Comment by michaelgeorgeattard** [comment]
Any updates on this please?

**Comment by jgw96** [comment]
Hello @michaelgeorgeattard Unfortunately we cannot seem to be able to reproduce on Chrome 53 (the latest stable) or firefox. If you could find a way to be able to reproduce this consistently in the first few times the menu is opened that would be great! Thanks!

**Comment by MiniGab** [comment]
@jgw96 I was able to reproduce the bug using Chrome 53. 

I made a recording : https://youtu.be/OgcEcHI6g80

You can start the video at 1 minute.

**Comment by jgw96** [comment]
@MiniGab Thanks for the video! After analyzing this more it seems that this is caused by a race condition that is being solved [here](https://github.com/driftyco/ionic/pull/8068). Because of this I will be closing this PR for now. Thanks for using Ionic!

**Comment by manucorporat** [comment]
@jgw96 it might not be the same error, in the video the content is the one that gets black.

I think the bug reported by @michaelgeorgeattard is not the same reported by @MiniGab

**Comment by manucorporat** [comment]
This bug was already fixed in RC0. z-index never gets to 0

**Pull request closed without merging**
