### PR TITLE
docs(fab): add docs variables SASS

### PR DESCRIPTION
**Pull request by ramonornela**
#### Changes proposed in this pull request:

**Ionic Version**: 2.0.0-rc.0

**Fixes**: #

### CODE REVIEW

**Comment by ramonornela** [comment]
Because other are capitalized (md, ios and wp)

**Comment by brandyscarney** [comment]
@ramonornela Sorry, I don't understand. I am asking if you could make them all `FAB`? The last two are written as `Fab`. Just to keep it consistent.

**Comment by brandyscarney** [comment]
Perfect. Thank you!

**Comment by ramonornela** [comment]
Thanks

Sorry I was driving at the moment, I only saw the first comments 😉

**Pull request merged**
