### PR TITLE
fix(popup): remove popup before showing previous

### LINKED ISSUE #4061: bug: isHighest causing problems with consecutive popups in v1.0.1
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello!

I'm facing a problem related to consecutive popups. You can simulate it through:
http://codepen.io/anon/pen/XbqWwB

Click on the button Test,then click save, the second popup will open, click save again. Now, try to click on the button Test again. It seems only the highest popup got closed, and the first popup remains in the DOM, but invisible. 

This issue didn't happen in 1.0.0

Here is the problem line:
https://github.com/driftyco/ionic/commit/8095b125152e85ba6f82a4350b77eef830dd5b29#diff-e91afb9d089c4a023017992e5bf71f3eR45574

I appreciate any attention over this issue. </span>

<span is-issue-template></span>

### PR DESCRIPTION
**Pull request by zittix**
Make sure to close and remove the currently shown popup before showing the previous one. Not doing that make the previous popup appear without hiding the current one. As a result, both popup cannot be closed.

It closes #4061.

The following code reproduces the problem:

```js
$timeout(function() {
	$ionicPopup.alert({
		title: "Popup 2",
	});
}, 1000);

$ionicPopup.alert({
	title: "Popup 1"
});
```

### CODE REVIEW

**Comment by olliebennett** [comment]
Hey @zittix, looks like you have a trailing space causing CI check to fail. Any chance you could fix (and perhaps rebase)?

**Comment by zittix** [comment]
@olliebennett I have fixed the trailing white space but failed to rebase. Let me know if you want me to open a new PR to clean that up.

**Comment by alextrs** [comment]
@zittix we have the exact the same problem and your fix helped. Hope it gets merged to master soon

**Comment by zittix** [comment]
:+1:

**Comment by AnthonyTsang** [comment]
Same problem

**Comment by zittix** [comment]
@olliebennett could you please review and merge this PR? Thanks.

**Comment by mhartington** [comment]
Awesome, thanks for the PR

**Comment by KevinGF** [comment]
:+1:

**Pull request closed without merging**
