### PR TITLE
Added ionTab disabled property and documented ionTab hidden property

### PR DESCRIPTION
**Pull request by beckyconning**

### CODE REVIEW

**Comment by perrygovier** [comment]
Thanks @beckyconning! I wound up creating something similar because navigating between tabs and regular pages didn't work as expected. This has been fixed in beta14. Would you say this is still necessary with that fixed? If so, how?

**Comment by beckyconning** [comment]
Can you share the fix commit?

**Comment by beckyconning** [comment]
Also please see https://github.com/driftyco/ionic/issues/2855 and https://github.com/beckyconning/ionic/commit/0031ecb0e30c335d9a270ea91cfc1cc0e5a0af52

**Comment by perrygovier** [comment]
Ah, I misunderstood the PR.  It's actually the hidden tab that we can probably get rid of now.  Disabled makes sense, especially since we have styles for it. 
If you get rid of the changes in `animations.scss`, I can add merge it in.

**Comment by beckyconning** [comment]
@perrygovier please merge https://github.com/beckyconning/ionic/commit/0031ecb0e30c335d9a270ea91cfc1cc0e5a0af52 instead

**Pull request closed without merging**
