### PR TITLE
chore(dgeni): fix deps dgeni-config

### PR DESCRIPTION
**Pull request by ramonornela**
#### Short description of what this resolves:
Fix deps dgeni run `gulp docs`

**Ionic Version**: nightly

### CODE REVIEW

**Comment by ramonornela** [comment]
Related #8165

**Comment by mhartington** [comment]
Please provide more information. What are you actually trying to fix? Is there an issue that you can reference.

**Comment by mhartington** [comment]
These modules were removed from master as generators are getting pulled out.
Closing as this is intended.

**Comment by ramonornela** [comment]
@mhartington yes in 2.0.0-beta11 there is deps usage in dgeni-config. 
Exists plans to @ionic-docs-dgeni with templates this is a great feature for use ;)

**Pull request closed without merging**
