### PR TITLE
Add isInstant to the closeOptionButtons method

### PR DESCRIPTION
**Pull request by TheBosZ**
Sometimes it would be nice to be able to have the buttons close instantly. This exposes the underlying listView's ability to do that.

### CODE REVIEW

**Comment by mhartington** [comment]
Closing this for now. Don't see any benefit of having this ATM.

**Comment by TheBosZ** [comment]
Why not? It's just exposing the underlying feature to close the options button.

**Comment by mhartington** [comment]
What's the benefit? Where would this come in handy?

**Comment by TheBosZ** [comment]
We have the case where a option button selection needed to close all buttons immediately. Yeah, I know it's not something that everyone would use every day, but since clearDragEffects() has the option anyway, it's nice to have a way to actually use it.

**Comment by mlynch** [comment]
Going to close for now, if people need this functionality they can use the patch here which looks nice, just don't see a need to add this in Ionic proper (plus v2 will handle this differently).

**Pull request closed without merging**
