### PR TITLE
fix(templates): suffix templates page #8320

### PR DESCRIPTION
**Pull request by ramonornela**
#### Short description of what this resolves:
Added suffix **Page** to templates generated by
```
ionic g page <mypage>
```
and
```
ionic g tabs <mypage>
```

#### Changes proposed in this pull request:

**Ionic Version**: 2.0.0-rc.0

**Fixes**: #8320

### CODE REVIEW

**Comment by ramonornela** [comment]
ping @danbucholtz

**Comment by danbucholtz** [comment]
@ramonornela,

Will validate and merge tonight.

Thanks,
Dan

**Comment by danbucholtz** [comment]
@mlynch, we were talking about this a bit earlier. Does this match with what you were imagining?

**Comment by ramonornela** [comment]
Related https://github.com/driftyco/ionic-app-generators/pull/2

**Pull request merged**
