### PR TITLE
fix issue #2775

### PR DESCRIPTION
**Pull request by AbraaoAlves**
Here [codepen-fixed](http://codepen.io/AbraaoAlves/pen/vExwdO).

### CODE REVIEW

**Comment by AbraaoAlves** [comment]
Close  #2775

**Comment by arcanis** [comment]
@AbraaoAlves you have to change the commit message for the travis CI to pass. Something like:

```
feat(items): add nav-direction support, fixes #2775
```

**Comment by AbraaoAlves** [comment]
Fixed,
Thanks @arcanis

**Comment by perrygovier** [comment]
LGTM, marking this for further testing

**Comment by Ionitron** [comment]
Greetings @AbraaoAlves!

Thank you very much from all of us on the Ionic team for submitting this pull request. We appreciate your commitment to improving Ionic. Unfortunately, we are unable to merge this particular PR, as it may cause regressions or is already out of date with regard to recent fixes. We apologize, as we know how much time you may have put into the work. 

We hope you will continue to contribute to Ionic in the future. Please note that we are more likely to merge a smaller PR that has a passing test and changes only one meaningful feature in the project. 

For more information, please review our [Pull Request Guidelines](http://ionicframework.com/contribute/#pull-request-guidelines).

Best regards,

Ionitron

**Pull request closed without merging**
