### PR TITLE
fix(button): menuToggle

### PR DESCRIPTION
**Pull request by manucorporat**
#### Changes proposed in this pull request:

-
-
-

**Ionic Version**: 1.x / 2.x

**Fixes**: #

### CODE REVIEW

**Comment by manucorporat** [comment]
@brandyscarney e2e test is missing though

**Comment by brandyscarney** [comment]
@manucorporat Thanks, I'll add one when I review this. 👍

**Comment by brandyscarney** [comment]
@manucorporat Can you test this on Windows Edge? We ran into an issue with menu toggle on edge where it was making all attributes lower case and therefore the styles weren't working, so I'm not sure if this will work on there.

**Comment by brandyscarney** [comment]
An alternative to this is using `menuToggle` as an `Input`:

```
 /**
  * @private
  */
@Input()
set menuToggle(val: any) {
  this._attr('_mt', 'menutoggle', true);
}
```

And then changing `_mt` to a  `string`. I also submitted a PR to move the logic out of button and into `menuToggle`. This could be tweaked further, but I think we should keep the styling as a class otherwise it is too specific of a selector. See: https://github.com/driftyco/ionic/pull/9314

**Pull request closed without merging**
