### PR TITLE
fix(util): ignore empty query param in getQueryString

### PR DESCRIPTION
**Pull request by ciekawy**
#### Short description of what this resolves:
ignores empty query param in getQueryString

#### Changes proposed in this pull request:

- filter out query params with no `=` character

**Ionic Version**: 2.x

**Fixes**: #5562

### CODE REVIEW

**Comment by adamdbradley** [comment]
Sorry, we actually do not have any unit tests for this method, but would you be able to add some tests to this file? https://github.com/driftyco/ionic/blob/2.0/ionic/util/test/util.spec.ts Thanks

**Comment by ciekawy** [comment]
sure, thanks for the suggestion! I've started to work on it and tried `gulp karma` and it gives me 
```
Chrome 48.0.2564 (Mac OS X 10.11.2) WARN: 'DEPRECATION WARNING: 'enqueueTask' is no longer supported and will be removed in next major release. Use addTask/addRepeatingTask/addMicroTask'

WARN [web-server]: 404: /base/ionic/ionic
WARN [web-server]: 404: /base/ionic/util
Chrome 48.0.2564 (Mac OS X 10.11.2) ERROR: 'Error: XHR error (404 Not Found) loading http://localhost:9876/base/ionic/ionic
    at o (http://localhost:9876/base/node_modules/systemjs/dist/system.js?ea2d7cecbce9a5de1b6777fa755578976b7f3e2b:4:12694)
    at XMLHttpRequest.s.onreadystatechange [as _onreadystatechange] (http://localhost:9876/base/node_modules/systemjs/dist/system.js?ea2d7cecbce9a5de1b6777fa755578976b7f3e2b:4:13219)
    at e.run (http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.min.js?9cdbe65010f0b9c01c79d3ecc028fea194341369:1:8725)
    at XMLHttpRequest.<anonymous> (http://localhost:9876/base/node_modules/angular2/bundles/angular2-polyfills.min.js?9cdbe65010f0b9c01c79d3ecc028fea194341369:1:8372)'

Chrome 48.0.2564 (Mac OS X 10.11.2): Executed 0 of 0 ERROR (0.001 secs / 0 secs)
```

Can you give me any hints?

**Comment by adamdbradley** [comment]
Sorry about that, we're updating the name of the ionic module to ionic-angular and must have missed getting the karma tests updated. I'll let you know when we get that fixed up, which should be pretty soon. Thanks

**Comment by adamdbradley** [comment]
Just got fixed, please pull down the latest and give it another shot, thanks

https://github.com/driftyco/ionic/commit/0cb080c9246c582b6fbec3ff804d6bc7361af639

**Comment by ciekawy** [comment]
Here are the tests for basic cases and for the #5562 issue as well. Please let know if think something is missing in this scope.

**Comment by adamdbradley** [comment]
thanks!

**Pull request merged**
