### PR TITLE
fix(util): array length check

### PR DESCRIPTION
**Pull request by dylanvdmerwe**
#### Short description of what this resolves:
Array out of bounds check in getQuerystring util

**Ionic Version**: 2.x

### CODE REVIEW

**Comment by adamdbradley** [comment]
thanks!

**Comment by adamdbradley** [comment]
What was the URL that was throwing the error for you?

**Comment by dylanvdmerwe** [comment]
It was weird. I was testing stuff with two form submits on the same page. In `ionic serve` it kept taking me to a URL like: `http://10.1.21.16/?` which was then breaking in that method.

**Comment by adamdbradley** [comment]
No problem. I added a few more unit tests and all looks good. thanks!

**Pull request merged**
