### PR TITLE
ToolbarItem directive not exported - breaks ngc 2.x

### PR DESCRIPTION
**Pull request by trik**
## 
## 
## 

**Ionic Version**: 1.x / 2.x

**Fixes**: #

references driftyco/ionic-app-scripts#214
still waiting for my t-shirt... :) M size please #ng-europe

### CODE REVIEW

**Comment by ramonornela** [comment]
ToolbarItem fix in https://github.com/driftyco/ionic/commit/98d474b879bbc507d294112524c98be762de1d33

**Comment by jordins** [comment]
I'm interested in this PR ... Could you merge this please?

**Comment by bjoernbur** [comment]
👍

**Comment by quickstar** [comment]
👍

**Comment by ramonornela** [comment]
TranslatePipe was removed https://github.com/driftyco/ionic/commit/339857af1e8b46ffebb70817546215b897fca1f0 adjust the PR

Thanks

**Pull request closed without merging**
