### PR TITLE
fix(dgeni): fix typo processor hide-private-api not run

### PR DESCRIPTION
**Pull request by ramonornela**
#### Short description of what this resolves:
Adjust  docs generation dgeni

#### Changes proposed in this pull request:

-
-
-

**Ionic Version**: 2.x

**Fixes**: #

### CODE REVIEW

**Comment by mhartington** [comment]
Hey there! Can you tell me a bit more about this? Why does this need to change? What is it breaking?

**Comment by ramonornela** [comment]
@mhartington run `gulp docs.dgeni` processor not run, is some change in dgeni.
Others processors has this standard (jekyll ... and all are executed).

**Comment by mhartington** [comment]
You should not be calling `gulp docs.dgeni` directly.

Still not seeing issues locally. Dgeni still runs and process the correct stuff. 

Closing since there is no errors.

**Comment by ramonornela** [comment]
@mhartington clean **node_modules** replace file [hide-private-api.js](https://gist.github.com/ramonornela/c2b4531589ee791f956461351732f51b) run process generation the console not run with this the privates api are exporteds.

**Comment by ramonornela** [comment]
Related #8166

**Pull request closed without merging**
