### PR TITLE
Update navbar transition for iOS

### PR DESCRIPTION
**Pull request by ttruong21**
#### Short description of what this resolves:
Update page transition

#### Changes proposed in this pull request:

- Better animation when we don't have nav bar in both leaving view and entering view

**Ionic Version**:  2.x

**Fixes**: #

- apply animation on enteringNavBar instead of enteringNavbarBg when current view does not have navbar and entering view has navbar
- apply animation on leavingNavBar instead of leavingNavbarBg when current view has navbar and entering view does not have navbar

### CODE REVIEW

**Comment by adamdbradley** [comment]
This will not transition well when going between two different colors of navbars. Could you describe more of why this is required?

**Comment by ttruong21** [comment]
The current transition is not good in iOS if the leaving page does not have navbar && the entering page has navbar && entering page has items (like buttons) in the navbar.

**Comment by adamdbradley** [comment]
Would you be able to create an example of what you mean? Something like these examples which test all the different scenarios? https://github.com/driftyco/ionic/tree/2.0/ionic/components/nav/test/basic Thanks

**Comment by jgw96** [comment]
Hey @ttruong21! We really appreciate your PR but since its been a little while since there was any activity on this PR i will be closing it for now. Thanks and feel free to submit more PR's in the future!

**Pull request closed without merging**
