### PR TITLE
fix(slides): inputs in slides handled correctly

### PR DESCRIPTION
**Pull request by jgw96**
#### Short description of what this resolves:

Currently the approach here is to treat inputs in slides like they are already in the viewable area. Slides have a complex structure and css that makes it hard for our current input focus scrolling implementation to know how far to scroll, if its in the viewable area etc etc. 

#### Changes proposed in this pull request:

- Treat inputs in slides like they are in the viewable area, this way we just focus it and call it done
- Make the paginator in slides stick to the bottom of the slides container. Without this the paginator ends up halfway up the page overlapping other elements.

**Ionic Version**: 2

**Fixes**: #9553

### CODE REVIEW

**Comment by jgw96** [comment]
Testing this issue with the latest nightly as there were a'lot of changes with slides lately.

**Comment by brandyscarney** [comment]
Can you update this PR to resolve conflicts and if you think it is ready to go remove the `WIP` label?

**Comment by airasheed** [comment]
Hi, I really appreciate this fix. Is there any update on this?

**Comment by brandyscarney** [comment]
Ping @jgw96

**Comment by jgw96** [comment]
updating this

**Comment by jgw96** [comment]
Going to close this PR for now, not entirely happy with the fix here and want to do re-do it from scratch.

**Comment by gsimonpotla** [comment]
Hi, would there be any update or workaround for this issue ?

**Comment by mikeyny** [comment]
@jgw96  Any Update on this issue ??

**Pull request closed without merging**
