### PR TITLE
Fix for issue 2521

### PR DESCRIPTION
**Pull request by elksson**
Please see comments on this pull request 
https://github.com/driftyco/ionic/pull/2988

### CODE REVIEW

**Comment by adamdbradley** [comment]
Can you please put together a codepen showing what it fixes, and one what devices/browsers/platforms? Display block may very well be there for a reason for a certain platform/browser. So while it may fix your scenario, I need to test it on all scenarios.

**Comment by 42shadow42** [comment]
I have created a code-pen showing what is broken. In the CSS section I have included commented CSS that simulates the fix as suggested. Please note disabling the removed styles in the debugger WILL NOT resolve the issue, but removing them from the CSS will.

http://codepen.io/42shadow42/pen/Jopozg

**Comment by adamdbradley** [comment]
Sorry but I'm not seeing the differences? On which device/browser/platform/version is the issue happening on? Can you provide a before and after screen shot?

**Comment by 42shadow42** [comment]
I encounter the issue in Chrome/Firefox/IE.
Before:
image
After:
image

Notice the title that says "Where did i go?" is not present in the first image.


Also if it helps, according to change logs.  The display: block; was added during commit 659e0e0a9e2ac9b91de783dd16ae99eb25216e92, which appears to be a CSS refactor. The notes indicate the flex styling was removed for being unnecessary.

**Comment by danbucholtz** [comment]
Hi @elksson,

This seems to be working.  Nice work.  Thanks for contributing to Ionic!

Thanks,
Dan

**Comment by alextrs** [comment]
This change breaks "grid" system in header. Take a look at http://codepen.io/alextrs/pen/RamWZO. Switch to previous version and you will see the expected behaviour.

Thanks

**Comment by amilino** [comment]
@alextrs +1

**Pull request merged**
