### PR TITLE
refactor(item): replaced attributes with item-start / item-end

### PR DESCRIPTION
**Pull request by AmitMY**
#### Short description of what this resolves:
Ambiguity in RTL projects.
Issue: 
https://github.com/driftyco/ionic/issues/11124

#### Changes proposed in this pull request:
- Change `item-left` to `item-start`
- Change `item-right` to `item-end`
- Deprecated SCSS variables with `-item-left` and created `-item-start`. same for `right`/`end`

**Ionic Version**: 3.1.x

### CODE REVIEW

**Comment by manucorporat** [comment]
Well, we can easily make this a non-breaking change.

- Let's add `item-left` and `item-right` back (as a deprecated util)
- We could add some logic to Item, so it prints a warning message when people use `item-right` or `item-left`.

**Comment by AmitMY** [comment]
@manucorporat That is possible, although, I have no idea what to do with:
https://github.com/AmitMY/ionic/blob/cb5ac7cfc1e2a9d49c2a696c120b37e4e3934500/src/components/item/item.ts#L277
https://github.com/AmitMY/ionic/blob/cb5ac7cfc1e2a9d49c2a696c120b37e4e3934500/src/components/item/item.ts#286

And where exactly to add the deprecation message.

The other thing for support, is just the 16 `.scss` files, which are easy fixes.

Do I also need to add /** @deprecated **/ above `.scss` selectors/variables that are deprecated? because I can't make someone not use the old `.scss` variables.

**Comment by brandyscarney** [comment]
I think this should behave the same everywhere:

`left` - Always left regardless of `dir`
`right` - Always right regardless of `dir`
`start` - The same as `left` if direction is `left-to-right` and `right` if direction is `right-to-left`.
`end` - The same as `right` if direction is `left-to-right` and `left` if direction is `right-to-left`.

This would make it so there are no breaking changes, and it improves support.

**Comment by AmitMY** [comment]
@brandyscarney While I agree with you on `text-X`, `icon-X`, `side` for menu and for sliding item, I disagree on this one.
The item's left and right are very strict things as far as I see them (currently, left is a separate container, while right is inside the main container etc, and those are not just rules)

On this one, I really believe there should be a deprecation for `left` and `right`.

Side note: I've seen you reviewed most rtl PRs. Can you please review this one as well? https://github.com/driftyco/ionic/pull/11121

**Comment by AmitMY** [comment]
@manucorporat @brandyscarney 
This is not longer a breaking change.
Both TS issue and SCSS variables were addressed.
Please let me know what else should be done, or if I got anything wrong, especially [here](https://github.com/driftyco/ionic/pull/11125/files#diff-13b951d9e1e2408913248b3447a8e03dR277) and [here](https://github.com/driftyco/ionic/pull/11125/files#diff-13b951d9e1e2408913248b3447a8e03dR286).

Need to update the official doc with new attributes, new scss variables, and to add a **deprecated** to the old variables.
This is just the start of variables naming changes, more to come in later PRs.

**Pull request merged**
