### PR TITLE
fix(SliderBox): do not resize if in cached view

### PR DESCRIPTION
**Pull request by edparsons**
I have a bug where I have a sliderbox in one tab and a button to open a modal in another. If you open the model from the other tab that triggers the resize on the sliderbox, which triggers the setup function. When this function tries to read the width of the sliderbox it gets zero and breaks the sliderbox. This code now check if any parent of the sliderbox is cached.

### CODE REVIEW

**Comment by weases** [comment]
Relates to #3245

**Comment by weases** [comment]
+1

**Comment by ivanmayes** [comment]
+1

**Comment by edparsons** [comment]
This was fix in radium-raccoon

**Pull request closed without merging**
