### PR TITLE
the title's height should respect the bar height

### PR DESCRIPTION
**Pull request by SidFerreira**
Faced this problem in an app.

### CODE REVIEW

**Comment by adamdbradley** [comment]
would you be able to put together a codepen showing the differences? Thanks

**Comment by SidFerreira** [comment]
Im a bit busy right now, but here's the issue: I had a project which header was 80px tall and the sub-header was 60px tall. I changed the header size to 80px, but noticed that the TOP for the sub-header was wrong, cause it uses the header height * 2 and a sum of the heights.

**Comment by SidFerreira** [comment]
I had a project which footer, header and subheader had different heights. Header was 80px, subheader was 60px and footer was 40px. The problem is that the titles used the header's height, so, subheader's title was 80px and footer's title too.

**Comment by mhartington** [comment]
@SidFerreira any luck putting together a codepen or demo to show the difference? Tested this out locally and it didn't seem to solve the issue you described

**Comment by SidFerreira** [comment]
I just took some time and created a project describing the issue:

    https://github.com/SidFerreira/funkyTitles

The project has custom sizes for the headers:

    $bar-height:						200px;
    $bar-footer-height:               	150px;
    $bar-subheader-height:            	100px;
    $bar-subfooter-height:            	70px;

You will see that the title will be based on 200 pixels.

**Comment by mhartington** [comment]
I think we'll pass on this one. It seems like a very particular use case and if people don't use sass, it will still cause issues.

**Pull request closed without merging**
